<?php
/**
 * ACF Theme Options & custom fields
 *
 * @package TCLAS
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

function tclas_register_acf_fields(): void {
	if ( ! function_exists( 'acf_add_options_page' ) ) {
		return;
	}

	acf_add_options_page( [
		'page_title' => 'TCLAS Theme options',
		'menu_title' => 'Theme options',
		'menu_slug'  => 'tclas-theme-options',
		'capability' => 'manage_options',
		'redirect'   => false,
		'icon_url'   => 'dashicons-flag',
	] );

	acf_add_options_sub_page( [
		'page_title'  => 'Illustrations',
		'menu_title'  => 'Illustrations',
		'parent_slug' => 'tclas-theme-options',
	] );

	acf_add_options_sub_page( [
		'page_title'  => 'Member Hub Settings',
		'menu_title'  => 'Member Hub',
		'menu_slug'   => 'tclas-hub-settings',
		'parent_slug' => 'tclas-theme-options',
	] );

	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	// ── Theme options field group ─────────────────────────────────────────
	acf_add_local_field_group( [
		'key'      => 'group_tclas_options',
		'title'    => 'TCLAS Theme options',
		'location' => [ [ [ 'param' => 'options_page', 'operator' => '==', 'value' => 'tclas-theme-options' ] ] ],
		'fields'   => [
			[
				'key'   => 'field_adobe_fonts_kit_id',
				'label' => 'Adobe Fonts kit ID',
				'name'  => 'adobe_fonts_kit_id',
				'type'  => 'text',
				'default_value' => 'pck6hdf',
				'instructions' => 'Get from Adobe Fonts → Web Projects. Default: pck6hdf (Skolar Sans).',
			],
			[
				'key'           => 'field_footer_logo',
				'label'         => 'Footer logo',
				'name'          => 'footer_logo',
				'type'          => 'image',
				'return_format' => 'array',
				'preview_size'  => 'thumbnail',
				'instructions'  => 'Light/inverted version of the logo for use on the dark footer background. If left blank, falls back to the site custom logo.',
			],
			[
				'key'   => 'field_footer_newsletter_form_id',
				'label' => 'Footer newsletter form ID',
				'name'  => 'footer_newsletter_form_id',
				'type'  => 'number',
				'default_value' => 0,
				'instructions' => 'Brevo form ID for the footer signup. Set after creating a form in the Brevo plugin.',
			],
			[
				'key'           => 'field_donate_form_id',
				'label'         => 'GiveWP donation form ID',
				'name'          => 'donate_form_id',
				'type'          => 'number',
				'default_value' => 0,
				'instructions'  => 'GiveWP form ID for the donate page. Create a form in Donations > Add Form, then enter its ID here.',
			],
			[
				'key'          => 'field_mapbox_access_token',
				'label'        => 'Mapbox access token',
				'name'         => 'mapbox_access_token',
				'type'         => 'text',
				'instructions' => 'Public access token from mapbox.com → Account → Tokens. Used for the ancestral commune map.',
			],
			[
				'key'          => 'field_mapbox_style_url',
				'label'        => 'Mapbox style URL',
				'name'         => 'mapbox_style_url',
				'type'         => 'text',
				'default_value' => 'mapbox://styles/tclas/cmmhutark001u01s98p0uakek',
				'instructions' => 'Style URL from Mapbox Studio (format: mapbox://styles/username/styleid).',
			],
			[
				'key'   => 'field_referral_base_url',
				'label' => 'Referral landing page URL',
				'name'  => 'referral_base_url',
				'type'  => 'url',
				'instructions' => 'URL of the referral welcome page, e.g. https://twincities.lu/welcome/. Leave blank to auto-detect.',
			],
			[
				'key'   => 'field_brevo_members_list_id',
				'label' => 'Brevo members list ID',
				'name'  => 'brevo_members_list_id',
				'type'  => 'number',
				'default_value' => 0,
				'instructions' => 'Brevo list ID for member sync. Used by FuseWP if manual overrides are needed.',
			],
			[
				'key'   => 'field_facebook_group_url',
				'label' => 'Facebook group URL',
				'name'  => 'facebook_group_url',
				'type'  => 'url',
				'default_value' => 'https://www.facebook.com/groups/tclas',
			],
			[
				'key'          => 'field_instagram_url',
				'label'        => 'Instagram URL',
				'name'         => 'instagram_url',
				'type'         => 'url',
				'instructions' => 'Full URL to the TCLAS Instagram profile. Shown in footer.',
			],
			[
				'key'          => 'field_linkedin_url',
				'label'        => 'LinkedIn URL',
				'name'         => 'linkedin_url',
				'type'         => 'url',
				'instructions' => 'Full URL to the TCLAS LinkedIn page. Shown in footer.',
			],
			[
				'key'   => 'field_national_day_mode',
				'label' => 'National Day mode',
				'name'  => 'national_day_mode',
				'type'  => 'true_false',
				'default_value' => 0,
				'instructions' => 'Enable flag stripe and special hero during Lëtzebuerger Nationalfeierdag season (June). Auto-detected within 7 days of June 23.',
				'ui'    => 1,
			],
			[
				'key'   => 'field_org_address',
				'label' => 'Organisation address',
				'name'  => 'org_address',
				'type'  => 'textarea',
				'rows'  => 3,
				'instructions' => 'Displayed in footer. Can be a mailing address or service area description.',
			],
			[
				'key'   => 'field_org_email',
				'label' => 'Contact email',
				'name'  => 'org_email',
				'type'  => 'email',
			],
			[
				'key'          => 'field_price_individual',
				'label'        => 'Individual membership price ($)',
				'name'         => 'price_individual',
				'type'         => 'number',
				'default_value' => 30,
				'min'          => 0,
				'instructions' => 'Annual price for Individual membership. Shown on the homepage membership section.',
			],
			[
				'key'          => 'field_price_family',
				'label'        => 'Family membership price ($)',
				'name'         => 'price_family',
				'type'         => 'number',
				'default_value' => 45,
				'min'          => 0,
				'instructions' => 'Annual price for Family membership.',
			],
			[
				'key'          => 'field_price_student',
				'label'        => 'Student membership price ($)',
				'name'         => 'price_student',
				'type'         => 'number',
				'default_value' => 15,
				'min'          => 0,
				'instructions' => 'Annual price for Student membership.',
			],
			// ── Homepage hero photo pairs ────────────────────────────────────
			[
				'key'          => 'field_hero_pairs',
				'label'        => 'Hero photo pairs',
				'name'         => 'hero_pairs',
				'type'         => 'repeater',
				'instructions' => 'Up to six Minnesota / Luxembourg photo pairs for the hero. Recommended size: 1600×900px (16:9). Municipality is required; photo credit is optional.',
				'layout'       => 'block',
				'max'          => 6,
				'button_label' => 'Add pair',
				'sub_fields'   => [
					[
						'key'           => 'field_hero_pairs_mn_photo',
						'label'         => 'Minnesota photo',
						'name'          => 'mn_photo',
						'type'          => 'image',
						'return_format' => 'array',
						'preview_size'  => 'medium',
						'instructions'  => 'Recommended: 1600×900px (16:9 landscape).',
						'wrapper'       => [ 'width' => '50' ],
					],
					[
						'key'           => 'field_hero_pairs_lux_photo',
						'label'         => 'Luxembourg photo',
						'name'          => 'lux_photo',
						'type'          => 'image',
						'return_format' => 'array',
						'preview_size'  => 'medium',
						'instructions'  => 'Recommended: 1600×900px (16:9 landscape).',
						'wrapper'       => [ 'width' => '50' ],
					],
					[
						'key'         => 'field_hero_pairs_mn_municipality',
						'label'       => 'MN municipality',
						'name'        => 'mn_municipality',
						'type'        => 'text',
						'required'    => 1,
						'placeholder' => 'e.g. Minneapolis',
						'wrapper'     => [ 'width' => '25' ],
					],
					[
						'key'          => 'field_hero_pairs_mn_credit',
						'label'        => 'MN photo credit',
						'name'         => 'mn_credit',
						'type'         => 'text',
						'placeholder'  => 'e.g. Photo: Jane Smith',
						'instructions' => 'Optional.',
						'wrapper'      => [ 'width' => '25' ],
					],
					[
						'key'         => 'field_hero_pairs_lux_municipality',
						'label'       => 'LUX municipality',
						'name'        => 'lux_municipality',
						'type'        => 'text',
						'required'    => 1,
						'placeholder' => 'e.g. Luxembourg City',
						'wrapper'     => [ 'width' => '25' ],
					],
					[
						'key'          => 'field_hero_pairs_lux_credit',
						'label'        => 'LUX photo credit',
						'name'         => 'lux_credit',
						'type'         => 'text',
						'placeholder'  => 'e.g. Photo: Visit Luxembourg',
						'instructions' => 'Optional.',
						'wrapper'      => [ 'width' => '25' ],
					],
					[
						'key'           => 'field_hero_pairs_mobile_image',
						'label'         => 'Mobile image',
						'name'          => 'mobile_image',
						'type'          => 'image',
						'return_format' => 'array',
						'preview_size'  => 'medium',
						'instructions'  => 'Optional. Portrait or square crop for mobile (portrait ratio recommended). Falls back to the Luxembourg photo if left empty.',
						'wrapper'       => [ 'width' => '50' ],
					],
				],
			],
			// ── Homepage stats ────────────────────────────────────────────────
			[
				'key'          => 'field_homepage_stats',
				'label'        => 'Homepage stats',
				'name'         => 'homepage_stats',
				'type'         => 'repeater',
				'layout'       => 'table',
				'min'          => 0,
				'max'          => 6,
				'button_label' => 'Add stat',
				'instructions' => 'The 4-cell strip beneath testimonials. Example: 300+ Members · 12+ Years · 40 Events per year · 150+ Citizen journeys supported.',
				'sub_fields'   => [
					[
						'key'         => 'field_homepage_stats_value',
						'label'       => 'Value',
						'name'        => 'stat_value',
						'type'        => 'text',
						'placeholder' => 'e.g. 300+',
						'wrapper'     => [ 'width' => '30' ],
					],
					[
						'key'         => 'field_homepage_stats_label',
						'label'       => 'Label',
						'name'        => 'stat_label',
						'type'        => 'text',
						'placeholder' => 'e.g. Members',
						'wrapper'     => [ 'width' => '70' ],
					],
				],
			],
			// ── Testimonials (shared: homepage + ancestry page) ───────────────
			[
				'key'          => 'field_testimonials',
				'label'        => 'Testimonials',
				'name'         => 'testimonials',
				'type'         => 'repeater',
				'layout'       => 'block',
				'min'          => 0,
				'button_label' => 'Add testimonial',
				'instructions' => 'Shared by the homepage (first 3) and the Ancestry page. Add at least 3 rows before the board preview.',
				'sub_fields'   => [
					[
						'key'   => 'field_testimonials_name',
						'label' => 'Name',
						'name'  => 'name',
						'type'  => 'text',
					],
					[
						'key'          => 'field_testimonials_member_since',
						'label'        => 'Member since',
						'name'         => 'member_since',
						'type'         => 'text',
						'placeholder'  => 'e.g. 2019',
						'instructions' => 'Year only.',
						'wrapper'      => [ 'width' => '50' ],
					],
					[
						'key'         => 'field_testimonials_location',
						'label'       => 'Location',
						'name'        => 'location',
						'type'        => 'text',
						'placeholder' => 'e.g. Minneapolis, MN',
						'wrapper'     => [ 'width' => '50' ],
					],
					[
						'key'           => 'field_testimonials_photo',
						'label'         => 'Photo',
						'name'          => 'photo',
						'type'          => 'image',
						'return_format' => 'array',
						'preview_size'  => 'thumbnail',
						'instructions'  => 'Square headshot, 200×200px or larger.',
					],
					[
						'key'          => 'field_testimonials_quote',
						'label'        => 'Quote',
						'name'         => 'quote',
						'type'         => 'textarea',
						'rows'         => 3,
						'instructions' => 'Do not include quotation marks — they will be added by the template.',
					],
				],
			],
		],
		[
			'key'          => 'field_ltz_terms',
			'label'        => 'Luxembourgish vocabulary',
			'name'         => 'ltz_terms',
			'type'         => 'repeater',
			'instructions' => 'Words and phrases to wrap in <span lang="lb">. List longer phrases before shorter words — multi-word phrases must come first. Leave empty to use the built-in fallback list. Changes apply within 12 hours (or after saving).',
			'layout'       => 'table',
			'button_label' => 'Add term',
			'sub_fields'   => [
				[
					'key'     => 'field_ltz_terms_ltz',
					'label'   => 'Luxembourgish term',
					'name'    => 'ltz_term',
					'type'    => 'text',
					'wrapper' => [ 'width' => '50' ],
				],
				[
					'key'          => 'field_ltz_terms_en',
					'label'        => 'English gloss',
					'name'         => 'en_translation',
					'type'         => 'text',
					'wrapper'      => [ 'width' => '50' ],
					'instructions' => 'Optional — for editorial reference only, not displayed on the site.',
				],
			],
		],
	] );

	// ── Illustrations field group ─────────────────────────────────────────
	acf_add_local_field_group( [
		'key'      => 'group_tclas_illustrations',
		'title'    => 'Illustrations',
		'location' => [ [ [ 'param' => 'options_page', 'operator' => '==', 'value' => 'tclas-theme-options-illustrations' ] ] ],
		'fields'   => [
			[
				'key'   => 'field_hero_illustration',
				'label' => 'Hero illustration (desktop)',
				'name'  => 'hero_illustration',
				'type'  => 'image',
				'return_format' => 'array',
				'preview_size'  => 'medium',
				'instructions'  => 'Recommended: 1440×640px PNG or SVG. Falls back to bundled hero.svg.',
			],
			[
				'key'   => 'field_hero_illustration_mobile',
				'label' => 'Hero illustration (mobile)',
				'name'  => 'hero_illustration_mobile',
				'type'  => 'image',
				'return_format' => 'array',
				'preview_size'  => 'medium',
				'instructions'  => 'Recommended: 640×640px portrait crop. Falls back to desktop version.',
			],
			[
				'key'   => 'field_welcome_illustration',
				'label' => 'Welcome section illustration',
				'name'  => 'welcome_illustration',
				'type'  => 'image',
				'return_format' => 'array',
				'preview_size'  => 'medium',
				'instructions'  => 'Recommended: ~480×480px. Interior gathering scene.',
			],
			[
				'key'   => 'field_membership_illustration',
				'label' => 'Membership section illustration',
				'name'  => 'membership_illustration',
				'type'  => 'image',
				'return_format' => 'array',
				'preview_size'  => 'medium',
				'instructions'  => 'Recommended: 1200×360px wide panoramic. Outdoor summer gathering.',
			],
			[
				'key'   => 'field_member_gate_illustration',
				'label' => 'Member gate illustration',
				'name'  => 'member_gate_illustration',
				'type'  => 'image',
				'return_format' => 'array',
				'preview_size'  => 'thumbnail',
				'instructions'  => 'Recommended: 320×320px. Friendly lion at a doorway.',
			],
			[
				'key'   => 'field_referral_lion_illustration',
				'label' => 'Referral card illustration',
				'name'  => 'referral_lion_illustration',
				'type'  => 'image',
				'return_format' => 'array',
				'preview_size'  => 'thumbnail',
				'instructions'  => 'Recommended: 160×160px. Lion holding an envelope.',
			],
		],
	] );

	// ── Luxembourg Story fields ───────────────────────────────────────────
	acf_add_local_field_group( [
		'key'      => 'group_tclas_story',
		'title'    => 'Story details',
		'location' => [ [ [ 'param' => 'post_type', 'operator' => '==', 'value' => 'tclas_story' ] ] ],
		'fields'   => [
			[
				'key'   => 'field_story_member_name',
				'label' => 'Member name',
				'name'  => 'story_member_name',
				'type'  => 'text',
				'instructions' => 'As you would like it to appear on the site.',
			],
			[
				'key'   => 'field_story_connection_type',
				'label' => 'Luxembourg connection',
				'name'  => 'story_connection_type',
				'type'  => 'checkbox',
				'choices' => [
					'ancestry'    => 'Family ancestry',
					'citizenship' => 'Citizenship / passport',
					'marriage'    => 'Married into a Luxembourg family',
					'work'        => 'Work / career connection',
					'travel'      => 'Frequent traveller / enthusiast',
					'culture'     => 'Food, language, culture',
				],
				'layout' => 'vertical',
			],
			[
				'key'   => 'field_story_immigration_generation',
				'label' => 'Immigration generation',
				'name'  => 'story_immigration_generation',
				'type'  => 'select',
				'choices' => [
					'1st'     => '1st generation (born in Luxembourg)',
					'2nd'     => '2nd generation (parents born in Luxembourg)',
					'3rd'     => '3rd generation',
					'4th'     => '4th generation',
					'further' => 'Further back',
					'na'      => 'Not applicable',
				],
				'allow_null' => 1,
			],
			[
				'key'   => 'field_story_citizenship_status',
				'label' => 'Citizenship / passport status',
				'name'  => 'story_citizenship_status',
				'type'  => 'select',
				'choices' => [
					'citizen'     => 'Luxembourg citizen',
					'in_progress' => 'Application in progress',
					'eligible'    => 'Eligible, not applied',
					'researching' => 'Researching eligibility',
					'na'          => 'Not applicable',
				],
				'allow_null' => 1,
			],
		],
	] );

	// ── Board member fields ───────────────────────────────────────────────
	acf_add_local_field_group( [
		'key'      => 'group_tclas_board',
		'title'    => 'Board member details',
		'location' => [ [ [ 'param' => 'post_type', 'operator' => '==', 'value' => 'tclas_board' ] ] ],
		'fields'   => [
			[
				'key'   => 'field_board_role',
				'label' => 'Role / title',
				'name'  => 'board_role',
				'type'  => 'text',
			],
			[
				'key'   => 'field_board_bio',
				'label' => 'Bio',
				'name'  => 'board_bio',
				'type'  => 'textarea',
				'rows'  => 4,
			],
			[
				'key'   => 'field_board_email',
				'label' => 'Contact email',
				'name'  => 'board_email',
				'type'  => 'email',
			],
		],
	] );

	// ── Commune profile fields (term meta) ────────────────────────────────
	acf_add_local_field_group( [
		'key'      => 'group_tclas_commune',
		'title'    => 'Commune Profile',
		'location' => [ [ [ 'param' => 'taxonomy', 'operator' => '==', 'value' => 'tclas_commune' ] ] ],
		'fields'   => [
			[
				'key'          => 'field_commune_wikipedia_url',
				'label'        => 'Wikipedia URL',
				'name'         => 'tclas_commune_wikipedia_url',
				'type'         => 'url',
				'instructions' => 'Link to the English or Luxembourgish Wikipedia article for this commune.',
			],
			[
				'key'          => 'field_commune_lux_website',
				'label'        => '.lu Official Website',
				'name'         => 'tclas_commune_lux_website_url',
				'type'         => 'url',
				'instructions' => 'Link to the official commune or municipal website on .lu domain.',
			],
		],
	] );

	// ── Department icons (term meta — Newsletter Browse by Topic, Phase 4) ──
	acf_add_local_field_group( [
		'key'      => 'group_tclas_department',
		'title'    => 'Department',
		'location' => [ [ [ 'param' => 'taxonomy', 'operator' => '==', 'value' => 'tclas_department' ] ] ],
		'fields'   => [
			[
				'key'           => 'field_department_icon',
				'label'         => 'Icon',
				'name'          => 'department_icon',
				'type'          => 'image',
				'return_format' => 'array',
				'preview_size'  => 'thumbnail',
				'instructions'  => 'SVG, PNG or WebP, 64×64px. Shown on the Newsletter Browse by Topic grid. Leave blank to render the card without an icon image.',
			],
		],
	] );

	// ── Newsletter / Loon & Lion — post fields ────────────────────────────
	acf_add_local_field_group( [
		'key'      => 'group_tclas_newsletter',
		'title'    => 'Loon & Lion Issue',
		'location' => [ [ [ 'param' => 'post_type', 'operator' => '==', 'value' => 'post' ] ] ],
		'fields'   => [
			[
				'key'          => 'field_tclas_issue_date',
				'label'        => 'Issue date',
				'name'         => 'tclas_issue_date',
				'type'         => 'text',
				'placeholder'  => 'YYYY-MM',
				'instructions' => 'Format: YYYY-MM (e.g. 2027-01). Groups this article with others in the same issue.',
			],
			[
				'key'          => 'field_tclas_issue_title',
				'label'        => 'Issue title',
				'name'         => 'tclas_issue_title',
				'type'         => 'text',
				'placeholder'  => 'e.g. The Loon & the Lion — March 2026',
				'instructions' => 'Display name for this issue. Shown on article pages above the headline. Falls back to a formatted date if left blank.',
			],
			[
				'key'           => 'field_tclas_issue_order',
				'label'         => 'Order within issue',
				'name'          => 'tclas_issue_order',
				'type'          => 'number',
				'default_value' => 99,
				'min'           => 1,
				'instructions'  => 'Lower numbers appear first in the table of contents. Main Story should be 1.',
			],
			[
				'key'           => 'field_tclas_byline',
				'label'         => 'Author byline',
				'name'          => 'tclas_byline',
				'type'          => 'text',
				'placeholder'   => 'e.g. Jane Smith',
				'instructions'  => 'Display name for the article author. Leave blank to use the WordPress post author. Set to "TCLAS" (or empty and check Hide) for institutional pieces.',
			],
			[
				'key'           => 'field_tclas_hide_byline',
				'label'         => 'Hide author byline',
				'name'          => 'tclas_hide_byline',
				'type'          => 'true_false',
				'default_value' => 0,
				'ui'            => 1,
				'instructions'  => 'Check to hide the byline entirely (e.g., for editorial or institutional content).',
			],
			[
				'key'           => 'field_tclas_members_only',
				'label'         => 'Members only',
				'name'          => '_tclas_members_only',
				'type'          => 'true_false',
				'default_value' => 0,
				'ui'            => 1,
				'instructions'  => 'Restrict this article to TCLAS members. Non-members will see a teaser with a prompt to join.',
			],
		],
	] );

	// ══════════════════════════════════════════════════════════════════════
	// PAGE-LEVEL EDITABLE CONTENT
	// Each field group is tied to a page template so its content can be
	// managed from the WordPress editor instead of editing PHP.
	// ══════════════════════════════════════════════════════════════════════

	// ── Homepage content ─────────────────────────────────────────────────
	acf_add_local_field_group( [
		'key'      => 'group_tclas_homepage',
		'title'    => 'Homepage content',
		'location' => [ [ [ 'param' => 'page_type', 'operator' => '==', 'value' => 'front_page' ] ] ],
		'fields'   => [
			// ── Hero copy blocks ─────────────────────────────────────────────
			[
				'key'          => 'field_hp_hero_tagline',
				'label'        => 'Hero tagline',
				'name'         => 'hp_hero_tagline',
				'type'         => 'text',
				'default_value' => 'A heritage that connects to modern Europe',
				'instructions' => 'Upper-right copy block (white text on ardoise). One punchy line.',
			],
			[
				'key'          => 'field_hp_hero_welcome',
				'label'        => 'Hero welcome text',
				'name'         => 'hp_hero_welcome',
				'type'         => 'textarea',
				'rows'         => 3,
				'default_value' => 'TCLAS brings together Americans of Luxembourgish descent, dual citizens, and expatriate Luxembourgers in the Twin Cities metro.',
				'instructions' => 'Lower-left copy block (1–2 sentences). Shown above the CTA buttons.',
			],
			[
				'key'          => 'field_hp_hero_cta1_label',
				'label'        => 'Hero CTA button 1 label',
				'name'         => 'hp_hero_cta1_label',
				'type'         => 'text',
				'default_value' => 'Join us',
				'instructions' => 'Primary CTA button in the hero lower-left block.',
				'wrapper'      => [ 'width' => '50' ],
			],
			[
				'key'          => 'field_hp_hero_cta1_url',
				'label'        => 'Hero CTA button 1 URL',
				'name'         => 'hp_hero_cta1_url',
				'type'         => 'text',
				'default_value' => '/join/',
				'instructions' => 'Relative or absolute URL.',
				'wrapper'      => [ 'width' => '50' ],
			],
			[
				'key'          => 'field_hp_hero_cta2_label',
				'label'        => 'Hero CTA button 2 label',
				'name'         => 'hp_hero_cta2_label',
				'type'         => 'text',
				'default_value' => 'Learn more',
				'instructions' => 'Secondary CTA button in the hero lower-left block.',
				'wrapper'      => [ 'width' => '50' ],
			],
			[
				'key'          => 'field_hp_hero_cta2_url',
				'label'        => 'Hero CTA button 2 URL',
				'name'         => 'hp_hero_cta2_url',
				'type'         => 'text',
				'default_value' => '/about/',
				'instructions' => 'Relative or absolute URL.',
				'wrapper'      => [ 'width' => '50' ],
			],
			// ── Mission section ──────────────────────────────────────────────
			[
				'key'          => 'field_hp_mission_body',
				'label'        => 'Mission paragraph',
				'name'         => 'hp_mission_body',
				'type'         => 'wysiwyg',
				'toolbar'      => 'basic',
				'media_upload' => 0,
				'tabs'         => 'visual',
				'instructions' => '"Who we are" section text. Supports bold, italic, and links.',
			],
			[
				'key'          => 'field_hp_cta_heading',
				'label'        => 'Citizenship CTA heading',
				'name'         => 'hp_cta_heading',
				'type'         => 'text',
				'instructions' => 'Default: "Think you might qualify?"',
			],
			[
				'key'          => 'field_hp_cta_body',
				'label'        => 'Citizenship CTA body',
				'name'         => 'hp_cta_body',
				'type'         => 'wysiwyg',
				'toolbar'      => 'basic',
				'media_upload' => 0,
				'tabs'         => 'visual',
				'instructions' => 'Paragraph beneath the citizenship CTA heading.',
			],
		],
	] );

	// ── Citizenship page content ─────────────────────────────────────────
	acf_add_local_field_group( [
		'key'      => 'group_tclas_citizenship',
		'title'    => 'Citizenship page content',
		'location' => [ [ [ 'param' => 'page_template', 'operator' => '==', 'value' => 'page-templates/page-citizenship.php' ] ] ],
		'fields'   => [
			[
				'key'          => 'field_cit_lede',
				'label'        => 'Introduction — first paragraph',
				'name'         => 'cit_lede',
				'type'         => 'wysiwyg',
				'toolbar'      => 'basic',
				'media_upload' => 0,
				'tabs'         => 'visual',
				'instructions' => 'The lede paragraph about the 2017 law.',
			],
			[
				'key'          => 'field_cit_lede_2',
				'label'        => 'Introduction — second paragraph',
				'name'         => 'cit_lede_2',
				'type'         => 'wysiwyg',
				'toolbar'      => 'basic',
				'media_upload' => 0,
				'tabs'         => 'visual',
				'instructions' => 'The paragraph about what the quiz does.',
			],
			[
				'key'          => 'field_cit_next_steps',
				'label'        => 'Next steps',
				'name'         => 'cit_next_steps',
				'type'         => 'repeater',
				'layout'       => 'block',
				'min'          => 1,
				'max'          => 8,
				'button_label' => 'Add step',
				'instructions' => 'Numbered steps shown after the quiz.',
				'sub_fields'   => [
					[
						'key'     => 'field_cit_step_title',
						'label'   => 'Title',
						'name'    => 'step_title',
						'type'    => 'text',
						'wrapper' => [ 'width' => '30' ],
					],
					[
						'key'          => 'field_cit_step_body',
						'label'        => 'Description',
						'name'         => 'step_body',
						'type'         => 'wysiwyg',
						'toolbar'      => 'basic',
						'media_upload' => 0,
						'tabs'         => 'visual',
						'wrapper'      => [ 'width' => '70' ],
					],
				],
			],
			[
				'key'          => 'field_cit_resources',
				'label'        => 'Official resources',
				'name'         => 'cit_resources',
				'type'         => 'repeater',
				'layout'       => 'block',
				'min'          => 1,
				'max'          => 8,
				'button_label' => 'Add resource',
				'instructions' => 'Link cards shown in the "Official resources" column.',
				'sub_fields'   => [
					[
						'key'           => 'field_cit_res_icon',
						'label'         => 'Icon',
						'name'          => 'res_icon',
						'type'          => 'select',
						'choices'       => [
							'globe2'             => 'Globe',
							'flag'               => 'Flag',
							'journal-text'       => 'Archive / Journal',
							'building-columns'   => 'Government',
							'clipboard-check'    => 'Clipboard',
							'file-earmark-text'  => 'Document',
							'envelope'           => 'Email',
							'telephone'          => 'Phone',
							'geo-alt'            => 'Location',
							'people'             => 'People',
							'book'               => 'Book',
							'link-45deg'         => 'Link',
							'info-circle'        => 'Info',
							'shield-check'       => 'Shield / Verified',
							'bank'               => 'Bank',
							'mortarboard'        => 'Education',
							'translate'          => 'Language',
						],
						'default_value' => 'globe2',
						'ui'            => 1,
						'return_format' => 'value',
						'instructions'  => 'Bootstrap Icon name.',
						'wrapper'       => [ 'width' => '15' ],
					],
					[
						'key'     => 'field_cit_res_name',
						'label'   => 'Name',
						'name'    => 'res_name',
						'type'    => 'text',
						'wrapper' => [ 'width' => '25' ],
					],
					[
						'key'     => 'field_cit_res_desc',
						'label'   => 'Description',
						'name'    => 'res_desc',
						'type'    => 'textarea',
						'rows'    => 2,
						'wrapper' => [ 'width' => '35' ],
					],
					[
						'key'     => 'field_cit_res_url',
						'label'   => 'URL',
						'name'    => 'res_url',
						'type'    => 'url',
						'wrapper' => [ 'width' => '25' ],
					],
				],
			],
			[
				'key'   => 'field_cit_community_heading',
				'label' => 'Community CTA heading',
				'name'  => 'cit_community_heading',
				'type'  => 'text',
				'instructions' => 'Default: "TCLAS members have been through it."',
			],
			[
				'key'          => 'field_cit_community_body',
				'label'        => 'Community CTA body',
				'name'         => 'cit_community_body',
				'type'         => 'wysiwyg',
				'toolbar'      => 'basic',
				'media_upload' => 0,
				'tabs'         => 'visual',
			],
		],
	] );

	// ── Join page content ────────────────────────────────────────────────
	acf_add_local_field_group( [
		'key'      => 'group_tclas_join',
		'title'    => 'Join page content',
		'location' => [ [ [ 'param' => 'page_template', 'operator' => '==', 'value' => 'page-templates/page-join.php' ] ] ],
		'fields'   => [
			[
				'key'          => 'field_join_lede',
				'label'        => 'Introduction',
				'name'         => 'join_lede',
				'type'         => 'wysiwyg',
				'toolbar'      => 'basic',
				'media_upload' => 0,
				'tabs'         => 'visual',
				'instructions' => 'Lede paragraph below the page header.',
			],
			[
				'key'          => 'field_join_tiers',
				'label'        => 'Tier taglines',
				'name'         => 'join_tiers',
				'type'         => 'repeater',
				'layout'       => 'table',
				'min'          => 3,
				'max'          => 3,
				'button_label' => 'Add tier',
				'instructions' => 'One row per tier: Individual, Family, Student/Senior. Order must match PMPro levels 1–3.',
				'sub_fields'   => [
					[
						'key'          => 'field_join_tier_key',
						'label'        => 'Tier',
						'name'         => 'tier_key',
						'type'         => 'text',
						'instructions' => 'Reference only (Individual / Family / Student).',
						'wrapper'      => [ 'width' => '20' ],
					],
					[
						'key'     => 'field_join_tier_invite',
						'label'   => 'Invitation tagline',
						'name'    => 'tier_invite',
						'type'    => 'text',
						'wrapper' => [ 'width' => '40' ],
					],
					[
						'key'          => 'field_join_tier_note',
						'label'        => 'Note',
						'name'         => 'tier_note',
						'type'         => 'text',
						'instructions' => 'Optional. E.g. "Covers up to four household members."',
						'wrapper'      => [ 'width' => '40' ],
					],
				],
			],
			[
				'key'          => 'field_join_perks',
				'label'        => 'Member perks',
				'name'         => 'join_perks',
				'type'         => 'repeater',
				'layout'       => 'block',
				'min'          => 1,
				'max'          => 10,
				'button_label' => 'Add perk',
				'instructions' => 'Cards in the "What you get" grid.',
				'sub_fields'   => [
					[
						'key'     => 'field_join_perk_title',
						'label'   => 'Title',
						'name'    => 'perk_title',
						'type'    => 'text',
						'wrapper' => [ 'width' => '30' ],
					],
					[
						'key'     => 'field_join_perk_desc',
						'label'   => 'Description',
						'name'    => 'perk_desc',
						'type'    => 'textarea',
						'rows'    => 3,
						'wrapper' => [ 'width' => '70' ],
					],
				],
			],
			[
				'key'          => 'field_join_volunteer_body',
				'label'        => 'Volunteer section',
				'name'         => 'join_volunteer_body',
				'type'         => 'wysiwyg',
				'toolbar'      => 'basic',
				'media_upload' => 0,
				'tabs'         => 'visual',
				'instructions' => 'Body text for the volunteer section.',
			],
			[
				'key'          => 'field_join_volunteer_email',
				'label'        => 'Volunteer contact email',
				'name'         => 'join_volunteer_email',
				'type'         => 'email',
				'instructions' => 'Used for the "Get in touch" button mailto link. Default: info@tclas.org.',
			],
			[
				'key'          => 'field_join_bottom_cta',
				'label'        => 'Bottom CTA body',
				'name'         => 'join_bottom_cta',
				'type'         => 'textarea',
				'rows'         => 2,
				'instructions' => 'Paragraph beneath the "Komm mat. / Come along." heading.',
			],
		],
	] );

	// ── MSP+LUX page content ─────────────────────────────────────────────
	$stat_sub_fields = [
		[
			'key'     => 'field_msp_stat_label',
			'label'   => 'Category',
			'name'    => 'stat_label',
			'type'    => 'text',
			'wrapper' => [ 'width' => '15' ],
		],
		[
			'key'     => 'field_msp_stat_mn_value',
			'label'   => 'MN value',
			'name'    => 'mn_value',
			'type'    => 'number',
			'wrapper' => [ 'width' => '10' ],
		],
		[
			'key'          => 'field_msp_stat_mn_format',
			'label'        => 'MN format',
			'name'         => 'mn_format',
			'type'         => 'select',
			'choices'      => [
				'int'   => 'Integer (428,000)',
				'pct'   => 'Percent (15%)',
				'year'  => 'Year (1867)',
				'm1'    => 'Millions 1dp (37.2M)',
				'm2'    => 'Millions 2dp (3.76M)',
				'usd-k' => 'USD thousands ($93K)',
			],
			'default_value' => 'int',
			'wrapper'       => [ 'width' => '10' ],
		],
		[
			'key'     => 'field_msp_stat_mn_note',
			'label'   => 'MN note',
			'name'    => 'mn_note',
			'type'    => 'text',
			'wrapper' => [ 'width' => '15' ],
		],
		[
			'key'          => 'field_msp_stat_mn_suffix',
			'label'        => 'MN suffix',
			'name'         => 'mn_suffix',
			'type'         => 'text',
			'instructions' => 'e.g. " AD"',
			'wrapper'      => [ 'width' => '5' ],
		],
		[
			'key'     => 'field_msp_stat_lux_value',
			'label'   => 'LUX value',
			'name'    => 'lux_value',
			'type'    => 'text',
			'instructions' => 'Number or emoji for non-numeric rows.',
			'wrapper' => [ 'width' => '10' ],
		],
		[
			'key'          => 'field_msp_stat_lux_format',
			'label'        => 'LUX format',
			'name'         => 'lux_format',
			'type'         => 'select',
			'choices'      => [
				'int'   => 'Integer (428,000)',
				'pct'   => 'Percent (15%)',
				'year'  => 'Year (1867)',
				'm1'    => 'Millions 1dp (37.2M)',
				'm2'    => 'Millions 2dp (3.76M)',
				'usd-k' => 'USD thousands ($93K)',
			],
			'default_value' => 'int',
			'wrapper'       => [ 'width' => '10' ],
		],
		[
			'key'     => 'field_msp_stat_lux_note',
			'label'   => 'LUX note',
			'name'    => 'lux_note',
			'type'    => 'text',
			'wrapper' => [ 'width' => '15' ],
		],
		[
			'key'          => 'field_msp_stat_lux_suffix',
			'label'        => 'LUX suffix',
			'name'         => 'lux_suffix',
			'type'         => 'text',
			'wrapper'      => [ 'width' => '5' ],
		],
		[
			'key'          => 'field_msp_stat_lux_is_emoji',
			'label'        => 'LUX is emoji',
			'name'         => 'lux_is_emoji',
			'type'         => 'true_false',
			'instructions' => 'Check if LUX value is an emoji/text instead of a number.',
			'wrapper'      => [ 'width' => '5' ],
		],
	];

	acf_add_local_field_group( [
		'key'      => 'group_tclas_msplux',
		'title'    => 'MSP+LUX page content',
		'location' => [ [ [ 'param' => 'page_template', 'operator' => '==', 'value' => 'page-templates/page-msp-lux.php' ] ] ],
		'fields'   => [
			[
				'key'          => 'field_msp_tagline',
				'label'        => 'Header tagline',
				'name'         => 'msp_tagline',
				'type'         => 'text',
				'instructions' => 'Default: "Two (relatively) small places that somehow end up leading the pack."',
			],
			// City comparison
			[
				'key'   => 'field_msp_city_mn_header',
				'label' => 'City table — MN header',
				'name'  => 'msp_city_mn_header',
				'type'  => 'text',
				'instructions' => 'Default: "Minneapolis".',
				'wrapper' => [ 'width' => '50' ],
			],
			[
				'key'   => 'field_msp_city_lux_header',
				'label' => 'City table — LUX header',
				'name'  => 'msp_city_lux_header',
				'type'  => 'text',
				'instructions' => 'Default: "Luxembourg City".',
				'wrapper' => [ 'width' => '50' ],
			],
			[
				'key'          => 'field_msp_city_stats',
				'label'        => 'City comparison stats',
				'name'         => 'msp_city_stats',
				'type'         => 'repeater',
				'layout'       => 'block',
				'max'          => 8,
				'button_label' => 'Add stat row',
				'sub_fields'   => $stat_sub_fields,
			],
			// Metro comparison
			[
				'key'   => 'field_msp_metro_mn_header',
				'label' => 'Metro table — MN header',
				'name'  => 'msp_metro_mn_header',
				'type'  => 'text',
				'instructions' => 'Default: "Twin Cities metro".',
				'wrapper' => [ 'width' => '50' ],
			],
			[
				'key'   => 'field_msp_metro_lux_header',
				'label' => 'Metro table — LUX header',
				'name'  => 'msp_metro_lux_header',
				'type'  => 'text',
				'instructions' => 'Default: "Luxembourg".',
				'wrapper' => [ 'width' => '50' ],
			],
			[
				'key'          => 'field_msp_metro_stats',
				'label'        => 'Metro comparison stats',
				'name'         => 'msp_metro_stats',
				'type'         => 'repeater',
				'layout'       => 'block',
				'max'          => 8,
				'button_label' => 'Add stat row',
				'sub_fields'   => $stat_sub_fields,
			],
			// Timeline
			[
				'key'          => 'field_msp_timeline',
				'label'        => 'Timeline items',
				'name'         => 'msp_timeline',
				'type'         => 'repeater',
				'layout'       => 'block',
				'max'          => 10,
				'button_label' => 'Add timeline item',
				'instructions' => '"The connections" history entries.',
				'sub_fields'   => [
					[
						'key'     => 'field_msp_tl_year',
						'label'   => 'Year / era',
						'name'    => 'tl_year',
						'type'    => 'text',
						'wrapper' => [ 'width' => '20' ],
					],
					[
						'key'     => 'field_msp_tl_title',
						'label'   => 'Title',
						'name'    => 'tl_title',
						'type'    => 'text',
						'wrapper' => [ 'width' => '30' ],
					],
					[
						'key'          => 'field_msp_tl_body',
						'label'        => 'Body',
						'name'         => 'tl_body',
						'type'         => 'wysiwyg',
						'toolbar'      => 'basic',
						'media_upload' => 0,
						'tabs'         => 'visual',
						'wrapper'      => [ 'width' => '50' ],
					],
				],
			],
			// Parallel Lives
			[
				'key'          => 'field_msp_parallels',
				'label'        => 'Parallel Lives cards',
				'name'         => 'msp_parallels',
				'type'         => 'repeater',
				'layout'       => 'block',
				'max'          => 8,
				'button_label' => 'Add card',
				'sub_fields'   => [
					[
						'key'         => 'field_msp_pl_icon',
						'label'       => 'Icon',
						'name'        => 'pl_icon',
						'type'        => 'text',
						'placeholder' => 'Emoji or HTML entity',
						'wrapper'     => [ 'width' => '15' ],
					],
					[
						'key'          => 'field_msp_pl_body',
						'label'        => 'Body',
						'name'         => 'pl_body',
						'type'         => 'wysiwyg',
						'toolbar'      => 'basic',
						'media_upload' => 0,
						'tabs'         => 'visual',
						'wrapper'      => [ 'width' => '85' ],
					],
				],
			],
			// Resources
			[
				'key'          => 'field_msp_resources_lux',
				'label'        => 'Luxembourg resources',
				'name'         => 'msp_resources_lux',
				'type'         => 'repeater',
				'layout'       => 'table',
				'max'          => 12,
				'button_label' => 'Add link',
				'sub_fields'   => [
					[
						'key'     => 'field_msp_rl_label',
						'label'   => 'Label',
						'name'    => 'res_label',
						'type'    => 'text',
						'wrapper' => [ 'width' => '50' ],
					],
					[
						'key'     => 'field_msp_rl_url',
						'label'   => 'URL',
						'name'    => 'res_url',
						'type'    => 'url',
						'wrapper' => [ 'width' => '50' ],
					],
				],
			],
			[
				'key'          => 'field_msp_resources_mn',
				'label'        => 'Minnesota resources',
				'name'         => 'msp_resources_mn',
				'type'         => 'repeater',
				'layout'       => 'table',
				'max'          => 12,
				'button_label' => 'Add link',
				'sub_fields'   => [
					[
						'key'     => 'field_msp_rm_label',
						'label'   => 'Label',
						'name'    => 'res_label',
						'type'    => 'text',
						'wrapper' => [ 'width' => '50' ],
					],
					[
						'key'     => 'field_msp_rm_url',
						'label'   => 'URL',
						'name'    => 'res_url',
						'type'    => 'url',
						'wrapper' => [ 'width' => '50' ],
					],
				],
			],
		],
	] );

	// ── Ancestry page content ────────────────────────────────────────────
	acf_add_local_field_group( [
		'key'      => 'group_tclas_ancestry',
		'title'    => 'Ancestry page content',
		'location' => [ [ [ 'param' => 'page_template', 'operator' => '==', 'value' => 'page-templates/page-ancestry.php' ] ] ],
		'fields'   => [
			[
				'key'          => 'field_anc_lede',
				'label'        => 'Introduction',
				'name'         => 'anc_lede',
				'type'         => 'wysiwyg',
				'toolbar'      => 'basic',
				'media_upload' => 0,
				'tabs'         => 'visual',
				'instructions' => 'Lede paragraph below the page header.',
			],
			[
				'key'          => 'field_anc_steps',
				'label'        => 'Research steps',
				'name'         => 'anc_steps',
				'type'         => 'repeater',
				'layout'       => 'block',
				'min'          => 1,
				'max'          => 10,
				'button_label' => 'Add step',
				'instructions' => 'Numbered research guide steps.',
				'sub_fields'   => [
					[
						'key'     => 'field_anc_step_title',
						'label'   => 'Title',
						'name'    => 'step_title',
						'type'    => 'text',
						'wrapper' => [ 'width' => '30' ],
					],
					[
						'key'          => 'field_anc_step_body',
						'label'        => 'Description',
						'name'         => 'step_body',
						'type'         => 'wysiwyg',
						'toolbar'      => 'basic',
						'media_upload' => 0,
						'tabs'         => 'visual',
						'wrapper'      => [ 'width' => '70' ],
					],
				],
			],
			[
				'key'          => 'field_anc_resources_lux',
				'label'        => 'Luxembourg archives',
				'name'         => 'anc_resources_lux',
				'type'         => 'repeater',
				'layout'       => 'table',
				'max'          => 12,
				'button_label' => 'Add link',
				'sub_fields'   => [
					[
						'key'     => 'field_anc_rl_label',
						'label'   => 'Label',
						'name'    => 'res_label',
						'type'    => 'text',
						'wrapper' => [ 'width' => '50' ],
					],
					[
						'key'     => 'field_anc_rl_url',
						'label'   => 'URL',
						'name'    => 'res_url',
						'type'    => 'url',
						'wrapper' => [ 'width' => '50' ],
					],
				],
			],
			[
				'key'          => 'field_anc_resources_us',
				'label'        => 'U.S. & Minnesota resources',
				'name'         => 'anc_resources_us',
				'type'         => 'repeater',
				'layout'       => 'table',
				'max'          => 12,
				'button_label' => 'Add link',
				'sub_fields'   => [
					[
						'key'     => 'field_anc_ru_label',
						'label'   => 'Label',
						'name'    => 'res_label',
						'type'    => 'text',
						'wrapper' => [ 'width' => '50' ],
					],
					[
						'key'     => 'field_anc_ru_url',
						'label'   => 'URL',
						'name'    => 'res_url',
						'type'    => 'url',
						'wrapper' => [ 'width' => '50' ],
					],
				],
			],
		],
	] );
	// ── Donate page content ─────────────────────────────────────────────
	acf_add_local_field_group( [
		'key'      => 'group_tclas_donate',
		'title'    => 'Donate page content',
		'location' => [ [ [ 'param' => 'page_template', 'operator' => '==', 'value' => 'page-templates/page-donate.php' ] ] ],
		'fields'   => [
			[
				'key'          => 'field_donate_lede',
				'label'        => 'Introduction',
				'name'         => 'donate_lede',
				'type'         => 'wysiwyg',
				'toolbar'      => 'basic',
				'media_upload' => 0,
				'tabs'         => 'visual',
				'instructions' => 'Lede paragraph below the page header. Why donations matter.',
			],
			[
				'key'          => 'field_donate_impact_items',
				'label'        => 'Impact items',
				'name'         => 'donate_impact_items',
				'type'         => 'repeater',
				'layout'       => 'block',
				'min'          => 1,
				'max'          => 6,
				'button_label' => 'Add impact item',
				'instructions' => '"Where your gift goes" cards. Each has a title and description.',
				'sub_fields'   => [
					[
						'key'     => 'field_donate_impact_title',
						'label'   => 'Title',
						'name'    => 'impact_title',
						'type'    => 'text',
						'wrapper' => [ 'width' => '30' ],
					],
					[
						'key'     => 'field_donate_impact_desc',
						'label'   => 'Description',
						'name'    => 'impact_desc',
						'type'    => 'textarea',
						'rows'    => 3,
						'wrapper' => [ 'width' => '70' ],
					],
				],
			],
			[
				'key'          => 'field_donate_tax_note',
				'label'        => 'Tax deductibility note',
				'name'         => 'donate_tax_note',
				'type'         => 'textarea',
				'rows'         => 2,
				'instructions' => 'Displayed below the donation form. E.g. "TCLAS is a 501(c)(3) nonprofit. Your gift is tax-deductible..."',
			],
		],
	] );
	// ── Member Hub settings field group ──────────────────────────────────
	acf_add_local_field_group( [
		'key'      => 'group_tclas_hub_settings',
		'title'    => 'Member Hub Settings',
		'location' => [ [ [ 'param' => 'options_page', 'operator' => '==', 'value' => 'tclas-hub-settings' ] ] ],
		'fields'   => [
			[
				'key'          => 'field_tclas_hub_featured_tab',
				'label'        => 'Featured Content',
				'type'         => 'tab',
			],
			[
				'key'          => 'field_tclas_featured_content',
				'label'        => 'Featured content items',
				'name'         => 'tclas_featured_content',
				'type'         => 'repeater',
				'instructions' => 'Manually curate the content shown in the "What\'s New" section of the member hub. Drag to reorder. If empty, events and newsletter issues are shown automatically.',
				'layout'       => 'table',
				'button_label' => 'Add Featured Item',
				'sub_fields'   => [
					[
						'key'     => 'field_tclas_fc_content_type',
						'label'   => 'Type',
						'name'    => 'content_type',
						'type'    => 'select',
						'choices' => [
							'event'      => 'Event',
							'newsletter' => 'Newsletter Issue',
						],
						'default_value' => 'newsletter',
						'wrapper' => [ 'width' => '25' ],
					],
					[
						'key'           => 'field_tclas_fc_content_id',
						'label'         => 'Content',
						'name'          => 'content_id',
						'type'          => 'post_object',
						'post_type'     => [ 'post', 'tribe_events' ],
						'return_format' => 'id',
						'ui'            => 1,
						'wrapper'       => [ 'width' => '75' ],
					],
				],
			],
			[
				'key'           => 'field_tclas_hub_featured_count',
				'label'         => 'Items to display',
				'name'          => 'tclas_hub_featured_count',
				'type'          => 'number',
				'default_value' => 5,
				'min'           => 3,
				'max'           => 10,
				'instructions'  => 'Number of items shown in the "What\'s New" section (3–10).',
			],
			[
				'key'           => 'field_tclas_hub_show_fallback',
				'label'         => 'Show fallback items',
				'name'          => 'tclas_hub_show_fallback',
				'type'          => 'true_false',
				'default_value' => 1,
				'ui'            => 1,
				'instructions'  => 'If featured items are fewer than the display count, fill remaining slots with upcoming events and recent newsletters.',
			],
			[
				'key'          => 'field_tclas_hub_digest_tab',
				'label'        => 'Weekly Digest',
				'type'         => 'tab',
			],
			[
				'key'           => 'field_tclas_digest_enabled',
				'label'         => 'Enable weekly digest emails',
				'name'          => 'tclas_digest_enabled',
				'type'          => 'true_false',
				'default_value' => 1,
				'ui'            => 1,
				'instructions'  => 'Send a weekly summary email to members with unread activity.',
			],
			[
				'key'           => 'field_tclas_digest_day',
				'label'         => 'Send day',
				'name'          => 'tclas_digest_day',
				'type'          => 'select',
				'choices'       => [
					'monday'    => 'Monday',
					'tuesday'   => 'Tuesday',
					'wednesday' => 'Wednesday',
					'thursday'  => 'Thursday',
					'friday'    => 'Friday',
					'saturday'  => 'Saturday',
					'sunday'    => 'Sunday',
				],
				'default_value' => 'monday',
				'instructions'  => 'Day of the week to send the digest.',
			],
			[
				'key'           => 'field_tclas_digest_time',
				'label'         => 'Send time',
				'name'          => 'tclas_digest_time',
				'type'          => 'text',
				'default_value' => '10:00',
				'instructions'  => 'Time to send (24-hour format, Central time). E.g. "10:00" for 10 AM.',
			],
		],
	] );
}
add_action( 'acf/init', 'tclas_register_acf_fields' );
