<?php
/**
 * Luxembourg commune data — generated from curated place-name spreadsheet.
 * 583 entries: villages, towns, and lieu-dits with precise coordinates.
 * Regenerated: 2026-03-05
 */
if ( ! defined( 'ABSPATH' ) ) exit;

function tclas_get_communes() {
    return [
        'abweiler' => [ 'name'=>'Abweiler', 'lux'=>'Obeler', 'municipality'=>'Bettembourg', 'canton'=>'Esch/Alzette', 'lat'=>49.5222, 'lng'=>6.1042 ],
        'ahn' => [ 'name'=>'Ahn', 'lux'=>'Ohn', 'municipality'=>'Wormeldange', 'canton'=>'Grevenmacher', 'lat'=>49.6294, 'lng'=>6.4194 ],
        'allerborn' => [ 'name'=>'Allerborn', 'lux'=>'Allerbuer', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0039, 'lng'=>5.8617 ],
        'alscheid' => [ 'name'=>'Alscheid', 'lux'=>'Alschent', 'municipality'=>'Kiischpelt', 'canton'=>'Wiltz', 'lat'=>49.9694, 'lng'=>6.0083 ],
        'altlinster' => [ 'name'=>'Altlinster', 'lux'=>'Allënster', 'municipality'=>'Junglinster', 'canton'=>'Grevenmacher', 'lat'=>49.7214, 'lng'=>6.2239 ],
        'altrier' => [ 'name'=>'Altrier', 'lux'=>'Schanz', 'municipality'=>'Bech', 'canton'=>'Echternach', 'lat'=>49.7503, 'lng'=>6.3267 ],
        'altwies' => [ 'name'=>'Altwies', 'lux'=>'Altwis', 'municipality'=>'Mondorf-les-Bains', 'canton'=>'Remich', 'lat'=>49.5108, 'lng'=>6.3297 ],
        'alzingen' => [ 'name'=>'Alzingen', 'lux'=>'Alzeng', 'municipality'=>'Hesperange', 'canton'=>'Luxembourg', 'lat'=>49.5678, 'lng'=>6.1611 ],
        'angelsberg' => [ 'name'=>'Angelsberg', 'lux'=>'Angelsbierg', 'municipality'=>'Fischbach', 'canton'=>'Mersch', 'lat'=>49.7639, 'lng'=>6.1583 ],
        'ansembourg' => [ 'name'=>'Ansembourg', 'lux'=>'Aansebuerg', 'municipality'=>'Helperknapp', 'canton'=>'Mersch', 'lat'=>49.7022, 'lng'=>6.0406 ],
        'arsdorf' => [ 'name'=>'Arsdorf', 'lux'=>'Ueschdref', 'municipality'=>'Rambrouch', 'canton'=>'Redange', 'lat'=>49.8600, 'lng'=>5.8450 ],
        'aspelt' => [ 'name'=>'Aspelt', 'lux'=>'Uespelt', 'municipality'=>'Frisange', 'canton'=>'Esch/Alzette', 'lat'=>49.5250, 'lng'=>6.2230 ],
        'assel' => [ 'name'=>'Assel', 'lux'=>'Aassel', 'municipality'=>'Bous', 'canton'=>'Remich', 'lat'=>49.5460, 'lng'=>6.2860 ],
        'asselborn' => [ 'name'=>'Asselborn', 'lux'=>'Aasselbuer', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0960, 'lng'=>5.9730 ],
        'asselscheuer' => [ 'name'=>'Asselscheuer', 'lux'=>'Aasselscheier', 'municipality'=>'Lorentzweiler', 'canton'=>'Mersch', 'lat'=>49.6970, 'lng'=>6.1360 ],
        'basbellain' => [ 'name'=>'Basbellain', 'lux'=>'Kierchen', 'municipality'=>'Troisvierges', 'canton'=>'Clervaux', 'lat'=>50.1430, 'lng'=>5.9780 ],
        'bascharage' => [ 'name'=>'Bascharage', 'lux'=>'Nidderkäerjeng', 'municipality'=>'Käerjeng', 'canton'=>'Capellen', 'lat'=>49.5667, 'lng'=>5.9167 ],
        'baschleiden' => [ 'name'=>'Baschleiden', 'lux'=>'Baschelt', 'municipality'=>'Boulaide', 'canton'=>'Wiltz', 'lat'=>49.8970, 'lng'=>5.8150 ],
        'bastendorf' => [ 'name'=>'Bastendorf', 'lux'=>'Baastenduerf', 'municipality'=>'Tandel', 'canton'=>'Vianden', 'lat'=>49.8900, 'lng'=>6.1640 ],
        'bavigne' => [ 'name'=>'Bavigne', 'lux'=>'Bidscht', 'municipality'=>'Lac de la Haute-Sûre', 'canton'=>'Wiltz', 'lat'=>49.9167, 'lng'=>5.8500 ],
        'beaufort' => [ 'name'=>'Beaufort', 'lux'=>'Befort', 'municipality'=>'Beaufort', 'canton'=>'Echternach', 'lat'=>49.8333, 'lng'=>6.2833 ],
        'bech' => [ 'name'=>'Bech', 'lux'=>'Bech', 'municipality'=>'Bech', 'canton'=>'Echternach', 'lat'=>49.7530, 'lng'=>6.3630 ],
        'bech-kleinmacher' => [ 'name'=>'Bech-Kleinmacher', 'lux'=>'Bech-Maacher', 'municipality'=>'Schengen', 'canton'=>'Remich', 'lat'=>49.5310, 'lng'=>6.3540 ],
        'beckerich' => [ 'name'=>'Beckerich', 'lux'=>'Biekerich', 'municipality'=>'Beckerich', 'canton'=>'Redange', 'lat'=>49.7330, 'lng'=>5.8830 ],
        'beggen' => [ 'name'=>'Beggen', 'lux'=>'Beggen', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6430, 'lng'=>6.1280 ],
        'beidweiler' => [ 'name'=>'Beidweiler', 'lux'=>'Beidweiler', 'municipality'=>'Junglinster', 'canton'=>'Grevenmacher', 'lat'=>49.7250, 'lng'=>6.3000 ],
        'beiler' => [ 'name'=>'Beiler', 'lux'=>'Bäiler', 'municipality'=>'Weiswampach', 'canton'=>'Clervaux', 'lat'=>50.1750, 'lng'=>6.0820 ],
        'belair' => [ 'name'=>'Belair', 'lux'=>'Belair', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6100, 'lng'=>6.1130 ],
        'belvaux' => [ 'name'=>'Belvaux', 'lux'=>'Beles', 'municipality'=>'Sanem', 'canton'=>'Esch/Alzette', 'lat'=>49.5167, 'lng'=>5.9333 ],
        'berbourg' => [ 'name'=>'Berbourg', 'lux'=>'Berbuerg', 'municipality'=>'Manternach', 'canton'=>'Grevenmacher', 'lat'=>49.7280, 'lng'=>6.3950 ],
        'berchem' => [ 'name'=>'Berchem', 'lux'=>'Bierchem', 'municipality'=>'Roeser', 'canton'=>'Luxembourg', 'lat'=>49.5410, 'lng'=>6.1280 ],
        'berdorf' => [ 'name'=>'Berdorf', 'lux'=>'Bäerdref', 'municipality'=>'Berdorf', 'canton'=>'Echternach', 'lat'=>49.8210, 'lng'=>6.3480 ],
        'bereldange' => [ 'name'=>'Bereldange', 'lux'=>'Bäreldeng', 'municipality'=>'Walferdange', 'canton'=>'Luxembourg', 'lat'=>49.6551, 'lng'=>6.1187 ],
        'berg' => [ 'name'=>'Berg', 'lux'=>'Bierg', 'municipality'=>'Colmar-Berg', 'canton'=>'Mersch', 'lat'=>49.8140, 'lng'=>6.0890 ],
        'bergem' => [ 'name'=>'Bergem', 'lux'=>'Biergem', 'municipality'=>'Mondercange', 'canton'=>'Esch/Alzette', 'lat'=>49.5250, 'lng'=>6.0400 ],
        'beringen' => [ 'name'=>'Beringen', 'lux'=>'Bereng', 'municipality'=>'Mersch', 'canton'=>'Mersch', 'lat'=>49.7580, 'lng'=>6.1120 ],
        'berle' => [ 'name'=>'Berlé', 'lux'=>'Bärel', 'municipality'=>'Winseler', 'canton'=>'Wiltz', 'lat'=>49.9522, 'lng'=>5.8561 ],
        'bertrange' => [ 'name'=>'Bertrange', 'lux'=>'Bartreng', 'municipality'=>'Bertrange', 'canton'=>'Luxembourg', 'lat'=>49.6111, 'lng'=>6.0500 ],
        'bettange-sur-mess' => [ 'name'=>'Bettange-sur-Mess', 'lux'=>'Betten op der Mess', 'municipality'=>'Dippach', 'canton'=>'Capellen', 'lat'=>49.5580, 'lng'=>5.9870 ],
        'bettborn' => [ 'name'=>'Bettborn', 'lux'=>'Bettborn', 'municipality'=>'Préizerdaul', 'canton'=>'Redange', 'lat'=>49.7970, 'lng'=>5.9350 ],
        'bettel' => [ 'name'=>'Bettel', 'lux'=>'Bettel', 'municipality'=>'Tandel', 'canton'=>'Vianden', 'lat'=>49.9160, 'lng'=>6.2250 ],
        'bettembourg' => [ 'name'=>'Bettembourg', 'lux'=>'Beetebuerg', 'municipality'=>'Bettembourg', 'canton'=>'Esch/Alzette', 'lat'=>49.5167, 'lng'=>6.1000 ],
        'bettendorf' => [ 'name'=>'Bettendorf', 'lux'=>'Bettenduerf', 'municipality'=>'Bettendorf', 'canton'=>'Diekirch', 'lat'=>49.8760, 'lng'=>6.2160 ],
        'betzdorf' => [ 'name'=>'Betzdorf', 'lux'=>'Betzdref', 'municipality'=>'Betzdorf', 'canton'=>'Grevenmacher', 'lat'=>49.6830, 'lng'=>6.3500 ],
        'beyren' => [ 'name'=>'Beyren', 'lux'=>'Beyeren', 'municipality'=>'Flaxweiler', 'canton'=>'Grevenmacher', 'lat'=>49.6264, 'lng'=>6.3369 ],
        'bigelbach' => [ 'name'=>'Bigelbach', 'lux'=>'Bigelbach', 'municipality'=>'Reisdorf', 'canton'=>'Diekirch', 'lat'=>49.8564, 'lng'=>6.2917 ],
        'bigonville' => [ 'name'=>'Bigonville', 'lux'=>'Bungeref', 'municipality'=>'Rambrouch', 'canton'=>'Redange', 'lat'=>49.8500, 'lng'=>5.7833 ],
        'bigonville-poteau' => [ 'name'=>'Bigonville-Poteau', 'lux'=>'Bungerefer Poteau', 'municipality'=>'Rambrouch', 'canton'=>'Redange', 'lat'=>49.8653, 'lng'=>5.7681 ],
        'bill' => [ 'name'=>'Bill', 'lux'=>'Bill', 'municipality'=>'Fischbach', 'canton'=>'Mersch', 'lat'=>49.7431, 'lng'=>6.1758 ],
        'bilsdorf' => [ 'name'=>'Bilsdorf', 'lux'=>'Bilschdref', 'municipality'=>'Rambrouch', 'canton'=>'Redange', 'lat'=>49.8580, 'lng'=>5.8230 ],
        'binsfeld' => [ 'name'=>'Binsfeld', 'lux'=>'Bënzelt', 'municipality'=>'Weiswampach', 'canton'=>'Clervaux', 'lat'=>50.1167, 'lng'=>6.0333 ],
        'birtrange' => [ 'name'=>'Birtrange', 'lux'=>'Biertreng', 'municipality'=>'Schieren', 'canton'=>'Diekirch', 'lat'=>49.8250, 'lng'=>6.0964 ],
        'bissen' => [ 'name'=>'Bissen', 'lux'=>'Biissen', 'municipality'=>'Bissen', 'canton'=>'Mersch', 'lat'=>49.7833, 'lng'=>6.0667 ],
        'bivange' => [ 'name'=>'Bivange', 'lux'=>'Biweng', 'municipality'=>'Roeser', 'canton'=>'Luxembourg', 'lat'=>49.5440, 'lng'=>6.1210 ],
        'bivels' => [ 'name'=>'Bivels', 'lux'=>'Biwels', 'municipality'=>'Putscheid', 'canton'=>'Vianden', 'lat'=>49.9583, 'lng'=>6.1833 ],
        'biwer' => [ 'name'=>'Biwer', 'lux'=>'Biwer', 'municipality'=>'Biwer', 'canton'=>'Grevenmacher', 'lat'=>49.7069, 'lng'=>6.3722 ],
        'biwerbach' => [ 'name'=>'Biwerbach', 'lux'=>'Biwerbaach', 'municipality'=>'Biwer', 'canton'=>'Grevenmacher', 'lat'=>49.7150, 'lng'=>6.3800 ],
        'biwisch' => [ 'name'=>'Biwisch', 'lux'=>'Biwesch', 'municipality'=>'Troisvierges', 'canton'=>'Clervaux', 'lat'=>50.1167, 'lng'=>5.9833 ],
        'blaschette' => [ 'name'=>'Blaschette', 'lux'=>'Blaaschent', 'municipality'=>'Lorentzweiler', 'canton'=>'Mersch', 'lat'=>49.7000, 'lng'=>6.1667 ],
        'blumenthal' => [ 'name'=>'Blumenthal', 'lux'=>'Blummendall', 'municipality'=>'Bech', 'canton'=>'Echternach', 'lat'=>49.7561, 'lng'=>6.2847 ],
        'bockholtz-goesdorf' => [ 'name'=>'Bockholtz (Goesdorf)', 'lux'=>'Boukels', 'municipality'=>'Goesdorf', 'canton'=>'Wiltz', 'lat'=>49.9167, 'lng'=>5.9667 ],
        'bockholtz-hosingen' => [ 'name'=>'Bockholtz (Hosingen)', 'lux'=>'Boukels', 'municipality'=>'Parc Hosingen', 'canton'=>'Clervaux', 'lat'=>49.9833, 'lng'=>6.0667 ],
        'boevange' => [ 'name'=>'Boevange', 'lux'=>'Béigen', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0500, 'lng'=>5.9333 ],
        'boevange-sur-attert' => [ 'name'=>'Boevange-sur-Attert', 'lux'=>'Béiwen-Atert', 'municipality'=>'Helperknapp', 'canton'=>'Mersch', 'lat'=>49.7750, 'lng'=>6.0150 ],
        'bofferdange' => [ 'name'=>'Bofferdange', 'lux'=>'Boufer', 'municipality'=>'Lorentzweiler', 'canton'=>'Mersch', 'lat'=>49.6833, 'lng'=>6.1333 ],
        'bollendorf-pont' => [ 'name'=>'Bollendorf-Pont', 'lux'=>'Bollendorfer Bréck', 'municipality'=>'Berdorf', 'canton'=>'Echternach', 'lat'=>49.8500, 'lng'=>6.3500 ],
        'bonnal' => [ 'name'=>'Bonnal', 'lux'=>'Bommel', 'municipality'=>'Lac de la Haute-Sûre', 'canton'=>'Wiltz', 'lat'=>49.8944, 'lng'=>5.8861 ],
        'bonnevoie' => [ 'name'=>'Bonnevoie', 'lux'=>'Bouneweg', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.5980, 'lng'=>6.1420 ],
        'born' => [ 'name'=>'Born', 'lux'=>'Bur', 'municipality'=>'Rosport-Mompach', 'canton'=>'Echternach', 'lat'=>49.7500, 'lng'=>6.5167 ],
        'boudler' => [ 'name'=>'Boudler', 'lux'=>'Buddeler', 'municipality'=>'Biwer', 'canton'=>'Grevenmacher', 'lat'=>49.6917, 'lng'=>6.3417 ],
        'boudlerbach' => [ 'name'=>'Boudlerbach', 'lux'=>'Buddelerbaach', 'municipality'=>'Biwer', 'canton'=>'Grevenmacher', 'lat'=>49.6972, 'lng'=>6.3361 ],
        'boulaide' => [ 'name'=>'Boulaide', 'lux'=>'Bauschelt', 'municipality'=>'Boulaide', 'canton'=>'Wiltz', 'lat'=>49.8833, 'lng'=>5.8167 ],
        'bour' => [ 'name'=>'Bour', 'lux'=>'Buer', 'municipality'=>'Helperknapp', 'canton'=>'Mersch', 'lat'=>49.7000, 'lng'=>6.0333 ],
        'bourglinster' => [ 'name'=>'Bourglinster', 'lux'=>'Buerglënster', 'municipality'=>'Junglinster', 'canton'=>'Grevenmacher', 'lat'=>49.7000, 'lng'=>6.2167 ],
        'bourscheid' => [ 'name'=>'Bourscheid', 'lux'=>'Buerschent', 'municipality'=>'Bourscheid', 'canton'=>'Diekirch', 'lat'=>49.9000, 'lng'=>6.0667 ],
        'bourscheid-moulin' => [ 'name'=>'Bourscheid-Moulin', 'lux'=>'Buerschter Millen', 'municipality'=>'Bourscheid', 'canton'=>'Diekirch', 'lat'=>49.9083, 'lng'=>6.0750 ],
        'bourscheid-plage' => [ 'name'=>'Bourscheid-Plage', 'lux'=>'Buerschter Plage', 'municipality'=>'Bourscheid', 'canton'=>'Diekirch', 'lat'=>49.9139, 'lng'=>6.0722 ],
        'boursdorf' => [ 'name'=>'Boursdorf', 'lux'=>'Buerschdrëf', 'municipality'=>'Rosport-Mompach', 'canton'=>'Echternach', 'lat'=>49.7750, 'lng'=>6.4667 ],
        'bous' => [ 'name'=>'Bous', 'lux'=>'Bous', 'municipality'=>'Bous-Waldbredimus', 'canton'=>'Remich', 'lat'=>49.5500, 'lng'=>6.3333 ],
        'boxhorn' => [ 'name'=>'Boxhorn', 'lux'=>'Boxhorn', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0833, 'lng'=>5.9833 ],
        'brachtenbach' => [ 'name'=>'Brachtenbach', 'lux'=>'Bruechtebaach', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0167, 'lng'=>5.9167 ],
        'brandenbourg' => [ 'name'=>'Brandenbourg', 'lux'=>'Branebuerg', 'municipality'=>'Tandel', 'canton'=>'Vianden', 'lat'=>49.9167, 'lng'=>6.1333 ],
        'brattert' => [ 'name'=>'Brattert', 'lux'=>'Brattert', 'municipality'=>'Wahl', 'canton'=>'Redange', 'lat'=>49.8333, 'lng'=>5.9333 ],
        'breidfeld' => [ 'name'=>'Breidfeld', 'lux'=>'Breedelt', 'municipality'=>'Weiswampach', 'canton'=>'Clervaux', 'lat'=>50.1333, 'lng'=>6.0500 ],
        'breidweiler' => [ 'name'=>'Breidweiler', 'lux'=>'Breedewéiler', 'municipality'=>'Consdorf', 'canton'=>'Echternach', 'lat'=>49.7833, 'lng'=>6.3000 ],
        'breinert' => [ 'name'=>'Breinert', 'lux'=>'Breinert', 'municipality'=>'Flaxweiler', 'canton'=>'Grevenmacher', 'lat'=>49.6583, 'lng'=>6.3417 ],
        'bricherhaff' => [ 'name'=>'Bricherhaff', 'lux'=>'Bricherhaff', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6250, 'lng'=>6.1583 ],
        'bridel' => [ 'name'=>'Bridel', 'lux'=>'Briddeler', 'municipality'=>'Kopstal', 'canton'=>'Capellen', 'lat'=>49.6500, 'lng'=>6.0833 ],
        'brouch-biwer' => [ 'name'=>'Brouch (Biwer)', 'lux'=>'Bruch', 'municipality'=>'Biwer', 'canton'=>'Grevenmacher', 'lat'=>49.7167, 'lng'=>6.3333 ],
        'brouch-helperknapp' => [ 'name'=>'Brouch (Helperknapp)', 'lux'=>'Bruch', 'municipality'=>'Helperknapp', 'canton'=>'Mersch', 'lat'=>49.7500, 'lng'=>6.0333 ],
        'buederscheid' => [ 'name'=>'Buederscheid', 'lux'=>'Büderschent', 'municipality'=>'Goesdorf', 'canton'=>'Wiltz', 'lat'=>49.9333, 'lng'=>5.9667 ],
        'burden' => [ 'name'=>'Burden', 'lux'=>'Bürden', 'municipality'=>'Erpeldange-sur-Sûre', 'canton'=>'Diekirch', 'lat'=>49.8833, 'lng'=>6.1000 ],
        'burmerange' => [ 'name'=>'Burmerange', 'lux'=>'Biermereng', 'municipality'=>'Schengen', 'canton'=>'Remich', 'lat'=>49.4833, 'lng'=>6.3167 ],
        'buschdorf' => [ 'name'=>'Buschdorf', 'lux'=>'Buschduerf', 'municipality'=>'Helperknapp', 'canton'=>'Mersch', 'lat'=>49.7833, 'lng'=>6.0167 ],
        'buschrodt' => [ 'name'=>'Buschrodt', 'lux'=>'Bouschtroff', 'municipality'=>'Wahl', 'canton'=>'Redange', 'lat'=>49.8333, 'lng'=>5.9333 ],
        'calmus' => [ 'name'=>'Calmus', 'lux'=>'Kaalmes', 'municipality'=>'Saeul', 'canton'=>'Redange', 'lat'=>49.7167, 'lng'=>5.9667 ],
        'canach' => [ 'name'=>'Canach', 'lux'=>'Kanech', 'municipality'=>'Lenningen', 'canton'=>'Remich', 'lat'=>49.6167, 'lng'=>6.3333 ],
        'capellen' => [ 'name'=>'Capellen', 'lux'=>'Kapellen', 'municipality'=>'Mamer', 'canton'=>'Capellen', 'lat'=>49.6333, 'lng'=>5.9833 ],
        'cents' => [ 'name'=>'Cents', 'lux'=>'Cents', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6167, 'lng'=>6.1667 ],
        'cessange' => [ 'name'=>'Cessange', 'lux'=>'Zéisseng', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.5910, 'lng'=>6.1080 ],
        'christnach' => [ 'name'=>'Christnach', 'lux'=>'Chrëschtnech', 'municipality'=>'Waldbillig', 'canton'=>'Echternach', 'lat'=>49.7881, 'lng'=>6.2734 ],
        'cinqfontaines' => [ 'name'=>'Cinqfontaines', 'lux'=>'Fünfbrunnen', 'municipality'=>'Troisvierges', 'canton'=>'Clervaux', 'lat'=>50.1111, 'lng'=>5.9750 ],
        'clausen' => [ 'name'=>'Clausen', 'lux'=>'Clausen', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6130, 'lng'=>6.1420 ],
        'claushof' => [ 'name'=>'Claushof', 'lux'=>'Claushof', 'municipality'=>'Helperknapp', 'canton'=>'Mersch', 'lat'=>49.7420, 'lng'=>6.0450 ],
        'clemency' => [ 'name'=>'Clemency', 'lux'=>'Kënzeg', 'municipality'=>'Käerjeng', 'canton'=>'Capellen', 'lat'=>49.5975, 'lng'=>5.8753 ],
        'clervaux' => [ 'name'=>'Clervaux', 'lux'=>'Klierf', 'municipality'=>'Clervaux', 'canton'=>'Clervaux', 'lat'=>50.0547, 'lng'=>6.0297 ],
        'cloche-dor' => [ 'name'=>'Cloche d\'Or', 'lux'=>'Cloche d\'Or', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.5820, 'lng'=>6.1150 ],
        'closdelt' => [ 'name'=>'Closdelt', 'lux'=>'Klosdelt', 'municipality'=>'Vianden', 'canton'=>'Vianden', 'lat'=>49.9250, 'lng'=>6.1830 ],
        'colbette' => [ 'name'=>'Colbette', 'lux'=>'Kolbet', 'municipality'=>'Bech', 'canton'=>'Echternach', 'lat'=>49.7667, 'lng'=>6.3167 ],
        'colmar-berg' => [ 'name'=>'Colmar-Berg', 'lux'=>'Colmar-Bierg', 'municipality'=>'Colmar-Berg', 'canton'=>'Mersch', 'lat'=>49.8142, 'lng'=>6.0969 ],
        'colmar-pont' => [ 'name'=>'Colmar-Pont', 'lux'=>'Colmar-Bréck', 'municipality'=>'Colmar-Berg', 'canton'=>'Mersch', 'lat'=>49.8080, 'lng'=>6.1150 ],
        'colpach-bas' => [ 'name'=>'Colpach-Bas', 'lux'=>'Nidderkolpech', 'municipality'=>'Ell', 'canton'=>'Redange', 'lat'=>49.7583, 'lng'=>5.8250 ],
        'colpach-haut' => [ 'name'=>'Colpach-Haut', 'lux'=>'Uewerkolpech', 'municipality'=>'Ell', 'canton'=>'Redange', 'lat'=>49.7667, 'lng'=>5.8250 ],
        'consdorf' => [ 'name'=>'Consdorf', 'lux'=>'Konsdref', 'municipality'=>'Consdorf', 'canton'=>'Echternach', 'lat'=>49.7789, 'lng'=>6.3364 ],
        'consthum' => [ 'name'=>'Consthum', 'lux'=>'Konstem', 'municipality'=>'Parc Hosingen', 'canton'=>'Clervaux', 'lat'=>49.9739, 'lng'=>6.0528 ],
        'contern' => [ 'name'=>'Contern', 'lux'=>'Conter', 'municipality'=>'Contern', 'canton'=>'Luxembourg', 'lat'=>49.5853, 'lng'=>6.2272 ],
        'crauthem' => [ 'name'=>'Crauthem', 'lux'=>'Krautem', 'municipality'=>'Roeser', 'canton'=>'Luxembourg', 'lat'=>49.5390, 'lng'=>6.1450 ],
        'crendal' => [ 'name'=>'Crendal', 'lux'=>'Krendel', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0570, 'lng'=>5.8970 ],
        'cruchten' => [ 'name'=>'Cruchten', 'lux'=>'Kruuchten', 'municipality'=>'Nommern', 'canton'=>'Mersch', 'lat'=>49.7925, 'lng'=>6.1303 ],
        'dahl' => [ 'name'=>'Dahl', 'lux'=>'Doll', 'municipality'=>'Goesdorf', 'canton'=>'Wiltz', 'lat'=>49.9344, 'lng'=>5.9786 ],
        'dahlem' => [ 'name'=>'Dahlem', 'lux'=>'Duelem', 'municipality'=>'Garnich', 'canton'=>'Capellen', 'lat'=>49.6022, 'lng'=>5.9483 ],
        'dalheim' => [ 'name'=>'Dalheim', 'lux'=>'Duelem', 'municipality'=>'Dalheim', 'canton'=>'Remich', 'lat'=>49.5408, 'lng'=>6.2597 ],
        'deiffelt' => [ 'name'=>'Deiffelt', 'lux'=>'Deewelt', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0656, 'lng'=>5.9639 ],
        'dellen' => [ 'name'=>'Dellen', 'lux'=>'Dellen', 'municipality'=>'Grosbous-Wal', 'canton'=>'Redange', 'lat'=>49.8550, 'lng'=>5.9640 ],
        'derenbach' => [ 'name'=>'Derenbach', 'lux'=>'Derenbach', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0120, 'lng'=>5.8900 ],
        'dickweiler' => [ 'name'=>'Dickweiler', 'lux'=>'Dickweiler', 'municipality'=>'Rosport-Mompach', 'canton'=>'Echternach', 'lat'=>49.7750, 'lng'=>6.4710 ],
        'diekirch' => [ 'name'=>'Diekirch', 'lux'=>'Dikrech', 'municipality'=>'Diekirch', 'canton'=>'Diekirch', 'lat'=>49.8681, 'lng'=>6.1567 ],
        'differdange' => [ 'name'=>'Differdange', 'lux'=>'Déifferdeng', 'municipality'=>'Differdange', 'canton'=>'Esch/Alzette', 'lat'=>49.5222, 'lng'=>5.8917 ],
        'dillingen' => [ 'name'=>'Dillingen', 'lux'=>'Délleng', 'municipality'=>'Beaufort', 'canton'=>'Echternach', 'lat'=>49.8540, 'lng'=>6.3180 ],
        'dippach' => [ 'name'=>'Dippach', 'lux'=>'Dippech', 'municipality'=>'Dippach', 'canton'=>'Capellen', 'lat'=>49.5872, 'lng'=>5.9817 ],
        'dirbach-bourscheid' => [ 'name'=>'Dirbach (Bourscheid)', 'lux'=>'Dirbech', 'municipality'=>'Bourscheid', 'canton'=>'Diekirch', 'lat'=>49.9175, 'lng'=>6.0336 ],
        'dirbach-goesdorf' => [ 'name'=>'Dirbach (Goesdorf)', 'lux'=>'Dirbech', 'municipality'=>'Goesdorf', 'canton'=>'Wiltz', 'lat'=>49.9210, 'lng'=>6.0300 ],
        'doennange' => [ 'name'=>'Doennange', 'lux'=>'Dinnent', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0667, 'lng'=>5.9667 ],
        'dommeldange' => [ 'name'=>'Dommeldange', 'lux'=>'Dummeldeng', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6330, 'lng'=>6.1380 ],
        'doncols' => [ 'name'=>'Doncols', 'lux'=>'Donkels', 'municipality'=>'Winseler', 'canton'=>'Wiltz', 'lat'=>49.9670, 'lng'=>5.8420 ],
        'dondelange' => [ 'name'=>'Dondelange', 'lux'=>'Dondel', 'municipality'=>'Kehlen', 'canton'=>'Capellen', 'lat'=>49.6800, 'lng'=>6.0333 ],
        'dorscheid' => [ 'name'=>'Dorscheid', 'lux'=>'Dorscht', 'municipality'=>'Parc Hosingen', 'canton'=>'Clervaux', 'lat'=>50.0250, 'lng'=>6.0833 ],
        'drauffelt' => [ 'name'=>'Drauffelt', 'lux'=>'Draufelt', 'municipality'=>'Clervaux', 'canton'=>'Clervaux', 'lat'=>49.9967, 'lng'=>6.0100 ],
        'dreiborn' => [ 'name'=>'Dreiborn', 'lux'=>'Dräibuer', 'municipality'=>'Wormeldange', 'canton'=>'Grevenmacher', 'lat'=>49.6380, 'lng'=>6.3980 ],
        'drinklange' => [ 'name'=>'Drinklange', 'lux'=>'Drénkelt', 'municipality'=>'Troisvierges', 'canton'=>'Clervaux', 'lat'=>50.1333, 'lng'=>6.0167 ],
        'dudderhaff' => [ 'name'=>'Dudderhaff', 'lux'=>'Dudderhaff', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6200, 'lng'=>6.1460 ],
        'dudelange' => [ 'name'=>'Dudelange', 'lux'=>'Diddeleng', 'municipality'=>'Dudelange', 'canton'=>'Esch/Alzette', 'lat'=>49.4833, 'lng'=>6.0833 ],
        'echternach' => [ 'name'=>'Echternach', 'lux'=>'Iechternach', 'municipality'=>'Echternach', 'canton'=>'Echternach', 'lat'=>49.8131, 'lng'=>6.4172 ],
        'ehlange' => [ 'name'=>'Ehlange', 'lux'=>'Éileng', 'municipality'=>'Reckange-sur-Mess', 'canton'=>'Esch/Alzette', 'lat'=>49.5530, 'lng'=>6.0230 ],
        'ehlerange' => [ 'name'=>'Ehlerange', 'lux'=>'Éilereng', 'municipality'=>'Sanem', 'canton'=>'Esch/Alzette', 'lat'=>49.5160, 'lng'=>5.9690 ],
        'ehnen' => [ 'name'=>'Ehnen', 'lux'=>'Éinen', 'municipality'=>'Wormeldange', 'canton'=>'Grevenmacher', 'lat'=>49.6014, 'lng'=>6.3853 ],
        'ehner' => [ 'name'=>'Ehner', 'lux'=>'Éiner', 'municipality'=>'Saeul', 'canton'=>'Redange', 'lat'=>49.7230, 'lng'=>5.9750 ],
        'eich' => [ 'name'=>'Eich', 'lux'=>'Eech', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6280, 'lng'=>6.1320 ],
        'eischen' => [ 'name'=>'Eischen', 'lux'=>'Äischen', 'municipality'=>'Habscht', 'canton'=>'Capellen', 'lat'=>49.6856, 'lng'=>5.8786 ],
        'eisenbach' => [ 'name'=>'Eisenbach', 'lux'=>'Eisenbaach', 'municipality'=>'Parc Hosingen', 'canton'=>'Clervaux', 'lat'=>49.9833, 'lng'=>6.1333 ],
        'eisenborn' => [ 'name'=>'Eisenborn', 'lux'=>'Eesebuer', 'municipality'=>'Junglinster', 'canton'=>'Grevenmacher', 'lat'=>49.6914, 'lng'=>6.1836 ],
        'ell' => [ 'name'=>'Ell', 'lux'=>'Ell', 'municipality'=>'Ell', 'canton'=>'Redange', 'lat'=>49.7610, 'lng'=>5.8530 ],
        'ellange' => [ 'name'=>'Ellange', 'lux'=>'Elleng', 'municipality'=>'Mondorf-les-Bains', 'canton'=>'Remich', 'lat'=>49.5181, 'lng'=>6.2994 ],
        'eltz' => [ 'name'=>'Eltz', 'lux'=>'Elz', 'municipality'=>'Redange/Attert', 'canton'=>'Redange', 'lat'=>49.7640, 'lng'=>5.8780 ],
        'elvange-beckerich' => [ 'name'=>'Elvange (Beckerich)', 'lux'=>'Elveng', 'municipality'=>'Beckerich', 'canton'=>'Redange', 'lat'=>49.7167, 'lng'=>5.9167 ],
        'elvange-schengen' => [ 'name'=>'Elvange (Schengen)', 'lux'=>'Elveng', 'municipality'=>'Schengen', 'canton'=>'Remich', 'lat'=>49.5042, 'lng'=>6.3150 ],
        'emerange' => [ 'name'=>'Emerange', 'lux'=>'Éimereng', 'municipality'=>'Schengen', 'canton'=>'Remich', 'lat'=>49.4833, 'lng'=>6.2833 ],
        'enscherange' => [ 'name'=>'Enscherange', 'lux'=>'Äischereng', 'municipality'=>'Kiischpelt', 'canton'=>'Wiltz', 'lat'=>49.9986, 'lng'=>5.9914 ],
        'enteschbach' => [ 'name'=>'Enteschbach', 'lux'=>'Enteschbaach', 'municipality'=>'Clervaux', 'canton'=>'Clervaux', 'lat'=>50.0333, 'lng'=>6.0667 ],
        'eppeldorf' => [ 'name'=>'Eppeldorf', 'lux'=>'Eppelduerf', 'municipality'=>'Vallée de l\'Ernz', 'canton'=>'Diekirch', 'lat'=>49.8517, 'lng'=>6.2464 ],
        'ermsdorf' => [ 'name'=>'Ermsdorf', 'lux'=>'Iermsdref', 'municipality'=>'Vallée de l\'Ernz', 'canton'=>'Diekirch', 'lat'=>49.8289, 'lng'=>6.2214 ],
        'ernster' => [ 'name'=>'Ernster', 'lux'=>'Eeschpelt', 'municipality'=>'Junglinster', 'canton'=>'Grevenmacher', 'lat'=>49.6833, 'lng'=>6.2500 ],
        'ernzen' => [ 'name'=>'Ernzen', 'lux'=>'Ierenz', 'municipality'=>'Larochette', 'canton'=>'Mersch', 'lat'=>49.7726, 'lng'=>6.2210 ],
        'erpeldange-bous' => [ 'name'=>'Erpeldange (Bous)', 'lux'=>'Ierpeldeng', 'municipality'=>'Bous-Waldbredimus', 'canton'=>'Remich', 'lat'=>49.5460, 'lng'=>6.3190 ],
        'erpeldange-wiltz' => [ 'name'=>'Erpeldange (Wiltz)', 'lux'=>'Ierpeldeng', 'municipality'=>'Wiltz', 'canton'=>'Wiltz', 'lat'=>49.9779, 'lng'=>5.9461 ],
        'erpeldange-sur-sure' => [ 'name'=>'Erpeldange-sur-Sûre', 'lux'=>'Ierpeldeng op der Sauer', 'municipality'=>'Erpeldange-sur-Sûre', 'canton'=>'Diekirch', 'lat'=>49.8639, 'lng'=>6.1139 ],
        'ersange' => [ 'name'=>'Ersange', 'lux'=>'Ierseng', 'municipality'=>'Bous-Waldbredimus', 'canton'=>'Remich', 'lat'=>49.5667, 'lng'=>6.2833 ],
        'esch-sur-alzette' => [ 'name'=>'Esch-sur-Alzette', 'lux'=>'Esch-Uelzecht', 'municipality'=>'Esch-sur-Alzette', 'canton'=>'Esch/Alzette', 'lat'=>49.4969, 'lng'=>5.9806 ],
        'esch-sur-sure' => [ 'name'=>'Esch-sur-Sûre', 'lux'=>'Esch-Sauer', 'municipality'=>'Esch-sur-Sûre', 'canton'=>'Wiltz', 'lat'=>49.9110, 'lng'=>5.9347 ],
        'eschdorf' => [ 'name'=>'Eschdorf', 'lux'=>'Eschduerf', 'municipality'=>'Esch-sur-Sûre', 'canton'=>'Wiltz', 'lat'=>49.8833, 'lng'=>5.9333 ],
        'eschette' => [ 'name'=>'Eschette', 'lux'=>'Eschpelt', 'municipality'=>'Rambrouch', 'canton'=>'Redange', 'lat'=>49.8228, 'lng'=>5.8867 ],
        'eschweiler-junglinster' => [ 'name'=>'Eschweiler (Junglinster)', 'lux'=>'Ischpelt', 'municipality'=>'Junglinster', 'canton'=>'Grevenmacher', 'lat'=>49.7167, 'lng'=>6.3000 ],
        'eschweiler-wiltz' => [ 'name'=>'Eschweiler (Wiltz)', 'lux'=>'Eschweiler', 'municipality'=>'Wiltz', 'canton'=>'Wiltz', 'lat'=>49.9972, 'lng'=>5.9472 ],
        'eselborn' => [ 'name'=>'Eselborn', 'lux'=>'Eselbuer', 'municipality'=>'Clervaux', 'canton'=>'Clervaux', 'lat'=>50.0667, 'lng'=>6.0000 ],
        'essingen' => [ 'name'=>'Essingen', 'lux'=>'Esseng', 'municipality'=>'Mersch', 'canton'=>'Mersch', 'lat'=>49.7333, 'lng'=>6.1167 ],
        'ettelbruck' => [ 'name'=>'Ettelbruck', 'lux'=>'Ettelbréck', 'municipality'=>'Ettelbruck', 'canton'=>'Diekirch', 'lat'=>49.8464, 'lng'=>6.0992 ],
        'everlange' => [ 'name'=>'Everlange', 'lux'=>'Ieverleng', 'municipality'=>'Useldange', 'canton'=>'Redange', 'lat'=>49.7667, 'lng'=>5.9500 ],
        'fennange' => [ 'name'=>'Fennange', 'lux'=>'Fenneng', 'municipality'=>'Bettembourg', 'canton'=>'Esch/Alzette', 'lat'=>49.5167, 'lng'=>6.0833 ],
        'fentange' => [ 'name'=>'Fentange', 'lux'=>'Fenteng', 'municipality'=>'Hesperange', 'canton'=>'Luxembourg', 'lat'=>49.5628, 'lng'=>6.1539 ],
        'fetschenhof' => [ 'name'=>'Fetschenhof', 'lux'=>'Fetschenhaff', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6100, 'lng'=>6.1500 ],
        'filsdorf' => [ 'name'=>'Filsdorf', 'lux'=>'Fëlschdref', 'municipality'=>'Dalheim', 'canton'=>'Remich', 'lat'=>49.5339, 'lng'=>6.2471 ],
        'findel' => [ 'name'=>'Findel', 'lux'=>'Findel', 'municipality'=>'Sandweiler', 'canton'=>'Luxembourg', 'lat'=>49.6333, 'lng'=>6.2167 ],
        'fingig' => [ 'name'=>'Fingig', 'lux'=>'Féiz', 'municipality'=>'Käerjeng', 'canton'=>'Capellen', 'lat'=>49.6000, 'lng'=>5.9000 ],
        'finsterthal' => [ 'name'=>'Finsterthal', 'lux'=>'Finstertall', 'municipality'=>'Helperknapp', 'canton'=>'Mersch', 'lat'=>49.7667, 'lng'=>6.0667 ],
        'fischbach-clervaux' => [ 'name'=>'Fischbach (Clervaux)', 'lux'=>'Fëschbech', 'municipality'=>'Clervaux', 'canton'=>'Clervaux', 'lat'=>50.0667, 'lng'=>6.0667 ],
        'fischbach-mersch' => [ 'name'=>'Fischbach (Mersch)', 'lux'=>'Fëschbech', 'municipality'=>'Fischbach', 'canton'=>'Mersch', 'lat'=>49.7333, 'lng'=>6.1833 ],
        'flatzbour' => [ 'name'=>'Flatzbour', 'lux'=>'Flatzbuer', 'municipality'=>'Rambrouch', 'canton'=>'Redange', 'lat'=>49.8400, 'lng'=>5.7900 ],
        'flaxweiler' => [ 'name'=>'Flaxweiler', 'lux'=>'Fluessweiler', 'municipality'=>'Flaxweiler', 'canton'=>'Grevenmacher', 'lat'=>49.6667, 'lng'=>6.3333 ],
        'flebour' => [ 'name'=>'Flebour', 'lux'=>'Fliebuer', 'municipality'=>'Boulaide', 'canton'=>'Wiltz', 'lat'=>49.8730, 'lng'=>5.8640 ],
        'foetz' => [ 'name'=>'Foetz', 'lux'=>'Féiz', 'municipality'=>'Mondercange', 'canton'=>'Esch/Alzette', 'lat'=>49.5244, 'lng'=>6.0111 ],
        'folkendange' => [ 'name'=>'Folkendange', 'lux'=>'Folkendeng', 'municipality'=>'Vallée de l\'Ernz', 'canton'=>'Diekirch', 'lat'=>49.8436, 'lng'=>6.2047 ],
        'folschette' => [ 'name'=>'Folschette', 'lux'=>'Folscht', 'municipality'=>'Rambrouch', 'canton'=>'Redange', 'lat'=>49.8142, 'lng'=>5.8731 ],
        'fossenhof' => [ 'name'=>'Fossenhof', 'lux'=>'Fossenhof', 'municipality'=>'Parc Hosingen', 'canton'=>'Clervaux', 'lat'=>50.1110, 'lng'=>6.0900 ],
        'fouhren' => [ 'name'=>'Fouhren', 'lux'=>'Fuuren', 'municipality'=>'Tandel', 'canton'=>'Vianden', 'lat'=>49.9142, 'lng'=>6.1961 ],
        'freckeisen' => [ 'name'=>'Freckeisen', 'lux'=>'Freckeisen', 'municipality'=>'Waldbillig', 'canton'=>'Echternach', 'lat'=>49.7928, 'lng'=>6.2556 ],
        'friedbusch' => [ 'name'=>'Friedbusch', 'lux'=>'Fridbësch', 'municipality'=>'Bourscheid', 'canton'=>'Diekirch', 'lat'=>49.9167, 'lng'=>6.1167 ],
        'frisange' => [ 'name'=>'Frisange', 'lux'=>'Fréiséng', 'municipality'=>'Frisange', 'canton'=>'Esch/Alzette', 'lat'=>49.5153, 'lng'=>6.1911 ],
        'garnich' => [ 'name'=>'Garnich', 'lux'=>'Garnech', 'municipality'=>'Garnich', 'canton'=>'Capellen', 'lat'=>49.6167, 'lng'=>5.9500 ],
        'gasperich' => [ 'name'=>'Gasperich', 'lux'=>'Gaasperech', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.5870, 'lng'=>6.1240 ],
        'geyershof' => [ 'name'=>'Geyershof', 'lux'=>'Geierhaff', 'municipality'=>'Bech', 'canton'=>'Echternach', 'lat'=>49.7833, 'lng'=>6.3667 ],
        'gilsdorf' => [ 'name'=>'Gilsdorf', 'lux'=>'Gilsduerf', 'municipality'=>'Bettendorf', 'canton'=>'Diekirch', 'lat'=>49.8667, 'lng'=>6.1833 ],
        'girst' => [ 'name'=>'Girst', 'lux'=>'Giischt', 'municipality'=>'Rosport-Mompach', 'canton'=>'Echternach', 'lat'=>49.7667, 'lng'=>6.5000 ],
        'girsterklaus' => [ 'name'=>'Girsterklaus', 'lux'=>'Giischterklaus', 'municipality'=>'Rosport-Mompach', 'canton'=>'Echternach', 'lat'=>49.7833, 'lng'=>6.5000 ],
        'givenich' => [ 'name'=>'Givenich', 'lux'=>'Giewenech', 'municipality'=>'Rosport-Mompach', 'canton'=>'Echternach', 'lat'=>49.7492, 'lng'=>6.4836 ],
        'godbrange' => [ 'name'=>'Godbrange', 'lux'=>'Guedber', 'municipality'=>'Junglinster', 'canton'=>'Grevenmacher', 'lat'=>49.7289, 'lng'=>6.2336 ],
        'goebelsmuhle' => [ 'name'=>'Goebelsmühle', 'lux'=>'Giewelsmillen', 'municipality'=>'Bourscheid', 'canton'=>'Diekirch', 'lat'=>49.9192, 'lng'=>6.0528 ],
        'goeblange' => [ 'name'=>'Goeblange', 'lux'=>'Giewel', 'municipality'=>'Koerich', 'canton'=>'Capellen', 'lat'=>49.6672, 'lng'=>5.9656 ],
        'goedange' => [ 'name'=>'Goedange', 'lux'=>'Géidgen', 'municipality'=>'Troisvierges', 'canton'=>'Clervaux', 'lat'=>50.1500, 'lng'=>6.0167 ],
        'goesdorf' => [ 'name'=>'Goesdorf', 'lux'=>'Géisdrëf', 'municipality'=>'Goesdorf', 'canton'=>'Wiltz', 'lat'=>49.9208, 'lng'=>5.9669 ],
        'goetzingen' => [ 'name'=>'Goetzingen', 'lux'=>'Gëtzen', 'municipality'=>'Koerich', 'canton'=>'Capellen', 'lat'=>49.6589, 'lng'=>5.9864 ],
        'gonderange' => [ 'name'=>'Gonderange', 'lux'=>'Gonneréng', 'municipality'=>'Junglinster', 'canton'=>'Grevenmacher', 'lat'=>49.6961, 'lng'=>6.2464 ],
        'gosseldange' => [ 'name'=>'Gosseldange', 'lux'=>'Gousseldeng', 'municipality'=>'Lintgen', 'canton'=>'Mersch', 'lat'=>49.7208, 'lng'=>6.1153 ],
        'gostingen' => [ 'name'=>'Gostingen', 'lux'=>'Goschteng', 'municipality'=>'Flaxweiler', 'canton'=>'Grevenmacher', 'lat'=>49.6200, 'lng'=>6.3508 ],
        'gralingen' => [ 'name'=>'Gralingen', 'lux'=>'Gralingen', 'municipality'=>'Putscheid', 'canton'=>'Vianden', 'lat'=>49.9333, 'lng'=>6.1333 ],
        'grass' => [ 'name'=>'Grass', 'lux'=>'Grass', 'municipality'=>'Steinfort', 'canton'=>'Capellen', 'lat'=>49.6333, 'lng'=>5.8917 ],
        'graulinster' => [ 'name'=>'Graulinster', 'lux'=>'Graulinster', 'municipality'=>'Junglinster', 'canton'=>'Grevenmacher', 'lat'=>49.7214, 'lng'=>6.2694 ],
        'greisch' => [ 'name'=>'Greisch', 'lux'=>'Gräisch', 'municipality'=>'Habscht', 'canton'=>'Capellen', 'lat'=>49.7139, 'lng'=>5.9892 ],
        'greiveldange' => [ 'name'=>'Greiveldange', 'lux'=>'Gréiweldeng', 'municipality'=>'Stadtbredimus', 'canton'=>'Remich', 'lat'=>49.5856, 'lng'=>6.3606 ],
        'grentzingen' => [ 'name'=>'Grentzingen', 'lux'=>'Grenzig', 'municipality'=>'Vallée de l\'Ernz', 'canton'=>'Diekirch', 'lat'=>49.8220, 'lng'=>6.2160 ],
        'grevels' => [ 'name'=>'Grevels', 'lux'=>'Gréiwels', 'municipality'=>'Grosbous-Wal', 'canton'=>'Redange', 'lat'=>49.8500, 'lng'=>5.9167 ],
        'grevenknapp' => [ 'name'=>'Grevenknapp', 'lux'=>'Gréiwenaap', 'municipality'=>'Helperknapp', 'canton'=>'Mersch', 'lat'=>49.7500, 'lng'=>6.0333 ],
        'grevenmacher' => [ 'name'=>'Grevenmacher', 'lux'=>'Gréiwemaacher', 'municipality'=>'Grevenmacher', 'canton'=>'Grevenmacher', 'lat'=>49.6797, 'lng'=>6.4414 ],
        'grindhausen' => [ 'name'=>'Grindhausen', 'lux'=>'Grandsen', 'municipality'=>'Clervaux', 'canton'=>'Clervaux', 'lat'=>50.0750, 'lng'=>6.0750 ],
        'grosbous' => [ 'name'=>'Grosbous', 'lux'=>'Groussbus', 'municipality'=>'Grosbous-Wal', 'canton'=>'Redange', 'lat'=>49.8292, 'lng'=>5.9642 ],
        'gruemelscheid' => [ 'name'=>'Gruemelscheid', 'lux'=>'Grëmmelescht', 'municipality'=>'Winseler', 'canton'=>'Wiltz', 'lat'=>49.9880, 'lng'=>5.8650 ],
        'grund' => [ 'name'=>'Grund', 'lux'=>'Gronn', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6067, 'lng'=>6.1367 ],
        'grundhof-beaufort' => [ 'name'=>'Grundhof (Beaufort)', 'lux'=>'Grondhaff', 'municipality'=>'Beaufort', 'canton'=>'Echternach', 'lat'=>49.8450, 'lng'=>6.3220 ],
        'grundhof-berdorf' => [ 'name'=>'Grundhof (Berdorf)', 'lux'=>'Grondhaff', 'municipality'=>'Berdorf', 'canton'=>'Echternach', 'lat'=>49.8497, 'lng'=>6.3269 ],
        'hachiville' => [ 'name'=>'Hachiville', 'lux'=>'Helzen', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.1111, 'lng'=>5.9225 ],
        'hagelsdorf' => [ 'name'=>'Hagelsdorf', 'lux'=>'Haidelsdref', 'municipality'=>'Biwer', 'canton'=>'Grevenmacher', 'lat'=>49.6917, 'lng'=>6.3722 ],
        'hagen' => [ 'name'=>'Hagen', 'lux'=>'Hoen', 'municipality'=>'Mamer', 'canton'=>'Capellen', 'lat'=>49.6487, 'lng'=>5.9302 ],
        'haller' => [ 'name'=>'Haller', 'lux'=>'Haler', 'municipality'=>'Waldbillig', 'canton'=>'Echternach', 'lat'=>49.8208, 'lng'=>6.2822 ],
        'hamiville' => [ 'name'=>'Hamiville', 'lux'=>'Heemicht', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0500, 'lng'=>5.9000 ],
        'hamm' => [ 'name'=>'Hamm', 'lux'=>'Hamm', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6100, 'lng'=>6.1667 ],
        'harlange' => [ 'name'=>'Harlange', 'lux'=>'Harel', 'municipality'=>'Lac de la Haute-Sûre', 'canton'=>'Wiltz', 'lat'=>49.9300, 'lng'=>5.7900 ],
        'hassel' => [ 'name'=>'Hassel', 'lux'=>'Haassel', 'municipality'=>'Weiler-la-Tour', 'canton'=>'Luxembourg', 'lat'=>49.5475, 'lng'=>6.2114 ],
        'haut-martelange' => [ 'name'=>'Haut-Martelange', 'lux'=>'Uewerkolpech', 'municipality'=>'Rambrouch', 'canton'=>'Redange', 'lat'=>49.8286, 'lng'=>5.7469 ],
        'hautbellain' => [ 'name'=>'Hautbellain', 'lux'=>'Beelen', 'municipality'=>'Troisvierges', 'canton'=>'Clervaux', 'lat'=>50.1667, 'lng'=>5.9833 ],
        'hautcharage' => [ 'name'=>'Hautcharage', 'lux'=>'Uewerkäerjeng', 'municipality'=>'Käerjeng', 'canton'=>'Capellen', 'lat'=>49.5761, 'lng'=>5.9125 ],
        'heffingen' => [ 'name'=>'Heffingen', 'lux'=>'Hiefenech', 'municipality'=>'Heffingen', 'canton'=>'Mersch', 'lat'=>49.7700, 'lng'=>6.2400 ],
        'heiderscheid' => [ 'name'=>'Heiderscheid', 'lux'=>'Heischent', 'municipality'=>'Esch-sur-Sûre', 'canton'=>'Wiltz', 'lat'=>49.8900, 'lng'=>5.9800 ],
        'heiderscheidergrund' => [ 'name'=>'Heiderscheidergrund', 'lux'=>'Heischent-Gronn', 'municipality'=>'Esch-sur-Sûre', 'canton'=>'Wiltz', 'lat'=>49.9167, 'lng'=>5.9667 ],
        'heinerscheid' => [ 'name'=>'Heinerscheid', 'lux'=>'Hengescht', 'municipality'=>'Clervaux', 'canton'=>'Clervaux', 'lat'=>50.1000, 'lng'=>6.0900 ],
        'heisdorf' => [ 'name'=>'Heisdorf', 'lux'=>'Heeschdrëf', 'municipality'=>'Steinsel', 'canton'=>'Luxembourg', 'lat'=>49.6700, 'lng'=>6.1400 ],
        'heispelt' => [ 'name'=>'Heispelt', 'lux'=>'Heispelt', 'municipality'=>'Wahl', 'canton'=>'Redange', 'lat'=>49.8500, 'lng'=>5.8800 ],
        'hellange' => [ 'name'=>'Hellange', 'lux'=>'Helleng', 'municipality'=>'Frisange', 'canton'=>'Esch/Alzette', 'lat'=>49.5075, 'lng'=>6.1511 ],
        'helmdange' => [ 'name'=>'Helmdange', 'lux'=>'Helmdeng', 'municipality'=>'Lorentzweiler', 'canton'=>'Mersch', 'lat'=>49.6936, 'lng'=>6.1428 ],
        'helmsange' => [ 'name'=>'Helmsange', 'lux'=>'Helmseng', 'municipality'=>'Walferdange', 'canton'=>'Luxembourg', 'lat'=>49.6631, 'lng'=>6.1367 ],
        'hemstal' => [ 'name'=>'Hemstal', 'lux'=>'Hemstal', 'municipality'=>'Bech', 'canton'=>'Echternach', 'lat'=>49.7431, 'lng'=>6.3314 ],
        'herborn' => [ 'name'=>'Herborn', 'lux'=>'Hierber', 'municipality'=>'Rosport-Mompach', 'canton'=>'Echternach', 'lat'=>49.7417, 'lng'=>6.4278 ],
        'hersberg' => [ 'name'=>'Hersberg', 'lux'=>'Heeschbreg', 'municipality'=>'Bech', 'canton'=>'Echternach', 'lat'=>49.7464, 'lng'=>6.3267 ],
        'hesperange' => [ 'name'=>'Hesperange', 'lux'=>'Hesper', 'municipality'=>'Hesperange', 'canton'=>'Luxembourg', 'lat'=>49.5739, 'lng'=>6.1539 ],
        'hierheck' => [ 'name'=>'Hierheck', 'lux'=>'Hierheck', 'municipality'=>'Esch-sur-Sûre', 'canton'=>'Wiltz', 'lat'=>49.8870, 'lng'=>5.9620 ],
        'hinkel' => [ 'name'=>'Hinkel', 'lux'=>'Hinckel', 'municipality'=>'Rosport-Mompach', 'canton'=>'Echternach', 'lat'=>49.7764, 'lng'=>6.5153 ],
        'hinterhassel' => [ 'name'=>'Hinterhassel', 'lux'=>'Hinterhassel', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0565, 'lng'=>5.8972 ],
        'hivange' => [ 'name'=>'Hivange', 'lux'=>'Hiweng', 'municipality'=>'Garnich', 'canton'=>'Capellen', 'lat'=>49.6000, 'lng'=>5.9300 ],
        'hobscheid' => [ 'name'=>'Hobscheid', 'lux'=>'Habscht', 'municipality'=>'Habscht', 'canton'=>'Capellen', 'lat'=>49.6900, 'lng'=>5.9100 ],
        'hoesdorf' => [ 'name'=>'Hoesdorf', 'lux'=>'Héisdrëf', 'municipality'=>'Reisdorf', 'canton'=>'Diekirch', 'lat'=>49.8800, 'lng'=>6.2600 ],
        'hoffelt' => [ 'name'=>'Hoffelt', 'lux'=>'Houfelt', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.1000, 'lng'=>5.9200 ],
        'hollenfels' => [ 'name'=>'Hollenfels', 'lux'=>'Huelmes', 'municipality'=>'Helperknapp', 'canton'=>'Mersch', 'lat'=>49.7100, 'lng'=>6.0500 ],
        'holler' => [ 'name'=>'Holler', 'lux'=>'Holler', 'municipality'=>'Weiswampach', 'canton'=>'Clervaux', 'lat'=>50.1200, 'lng'=>6.0500 ],
        'hollerich' => [ 'name'=>'Hollerich', 'lux'=>'Hollerech', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6000, 'lng'=>6.1100 ],
        'hollermuhle' => [ 'name'=>'Hollermühle', 'lux'=>'Hollermillen', 'municipality'=>'Weiswampach', 'canton'=>'Clervaux', 'lat'=>50.1167, 'lng'=>6.0333 ],
        'holtz' => [ 'name'=>'Holtz', 'lux'=>'Holtz', 'municipality'=>'Rambrouch', 'canton'=>'Redange', 'lat'=>49.8100, 'lng'=>5.7900 ],
        'holzem' => [ 'name'=>'Holzem', 'lux'=>'Holzem', 'municipality'=>'Mamer', 'canton'=>'Capellen', 'lat'=>49.6200, 'lng'=>5.9900 ],
        'holzthum' => [ 'name'=>'Holzthum', 'lux'=>'Holztum', 'municipality'=>'Parc Hosingen', 'canton'=>'Clervaux', 'lat'=>49.9800, 'lng'=>6.0700 ],
        'hoscheid' => [ 'name'=>'Hoscheid', 'lux'=>'Houschent', 'municipality'=>'Parc Hosingen', 'canton'=>'Clervaux', 'lat'=>49.9500, 'lng'=>6.0800 ],
        'hoscheid-dickt' => [ 'name'=>'Hoscheid-Dickt', 'lux'=>'Houschter Dickt', 'municipality'=>'Parc Hosingen', 'canton'=>'Clervaux', 'lat'=>49.9700, 'lng'=>6.0900 ],
        'hoscheidterhof' => [ 'name'=>'Hoscheidterhof', 'lux'=>'Houschterhaff', 'municipality'=>'Putscheid', 'canton'=>'Vianden', 'lat'=>49.9400, 'lng'=>6.1600 ],
        'hosingen' => [ 'name'=>'Hosingen', 'lux'=>'Housen', 'municipality'=>'Parc Hosingen', 'canton'=>'Clervaux', 'lat'=>50.0167, 'lng'=>6.0833 ],
        'hostert-niederanven' => [ 'name'=>'Hostert (Niederanven)', 'lux'=>'Hueschtert', 'municipality'=>'Niederanven', 'canton'=>'Luxembourg', 'lat'=>49.6600, 'lng'=>6.2300 ],
        'hostert-rambrouch' => [ 'name'=>'Hostert (Rambrouch)', 'lux'=>'Hueschtert', 'municipality'=>'Rambrouch', 'canton'=>'Redange', 'lat'=>49.8100, 'lng'=>5.8700 ],
        'hovelange' => [ 'name'=>'Hovelange', 'lux'=>'Huewel', 'municipality'=>'Beckerich', 'canton'=>'Redange', 'lat'=>49.7200, 'lng'=>5.9100 ],
        'howald' => [ 'name'=>'Howald', 'lux'=>'Houwald', 'municipality'=>'Hesperange', 'canton'=>'Luxembourg', 'lat'=>49.5800, 'lng'=>6.1400 ],
        'huettermuehle' => [ 'name'=>'Huettermuehle', 'lux'=>'Hëttermillen', 'municipality'=>'Stadtbredimus', 'canton'=>'Remich', 'lat'=>49.5900, 'lng'=>6.3700 ],
        'huldange' => [ 'name'=>'Huldange', 'lux'=>'Huldang', 'municipality'=>'Weiswampach', 'canton'=>'Clervaux', 'lat'=>50.1667, 'lng'=>6.0167 ],
        'huncherange' => [ 'name'=>'Huncherange', 'lux'=>'Hënchereng', 'municipality'=>'Bettembourg', 'canton'=>'Esch/Alzette', 'lat'=>49.5167, 'lng'=>6.0667 ],
        'hunsdorf' => [ 'name'=>'Hunsdorf', 'lux'=>'Hënsdref', 'municipality'=>'Lorentzweiler', 'canton'=>'Mersch', 'lat'=>49.6833, 'lng'=>6.1167 ],
        'hupperdange' => [ 'name'=>'Hupperdange', 'lux'=>'Hipperdang', 'municipality'=>'Clervaux', 'canton'=>'Clervaux', 'lat'=>50.0933, 'lng'=>6.0600 ],
        'huttange' => [ 'name'=>'Huttange', 'lux'=>'Hütteng', 'municipality'=>'Beckerich', 'canton'=>'Redange', 'lat'=>49.7333, 'lng'=>5.8833 ],
        'imbringen' => [ 'name'=>'Imbringen', 'lux'=>'Amber', 'municipality'=>'Junglinster', 'canton'=>'Grevenmacher', 'lat'=>49.7117, 'lng'=>6.1628 ],
        'ingeldorf' => [ 'name'=>'Ingeldorf', 'lux'=>'Angelduerf', 'municipality'=>'Erpeldange-sur-Sûre', 'canton'=>'Diekirch', 'lat'=>49.8500, 'lng'=>6.1333 ],
        'insenborn' => [ 'name'=>'Insenborn', 'lux'=>'Ensber', 'municipality'=>'Esch-sur-Sûre', 'canton'=>'Wiltz', 'lat'=>49.8917, 'lng'=>5.8864 ],
        'itzig' => [ 'name'=>'Itzig', 'lux'=>'Izeg', 'municipality'=>'Hesperange', 'canton'=>'Luxembourg', 'lat'=>49.5858, 'lng'=>6.1731 ],
        'juegdschlass' => [ 'name'=>'Juegdschlass', 'lux'=>'Juegdschlass', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6450, 'lng'=>6.1150 ],
        'junglinster' => [ 'name'=>'Junglinster', 'lux'=>'Jonglënster', 'municipality'=>'Junglinster', 'canton'=>'Grevenmacher', 'lat'=>49.7119, 'lng'=>6.2514 ],
        'kaaspelterhof' => [ 'name'=>'Kaaspelterhof', 'lux'=>'Kaaspelterhaff', 'municipality'=>'Kiischpelt', 'canton'=>'Wiltz', 'lat'=>49.9800, 'lng'=>5.9800 ],
        'kaesfurt' => [ 'name'=>'Kaesfurt', 'lux'=>'Kisfurt', 'municipality'=>'Clervaux', 'canton'=>'Clervaux', 'lat'=>50.0833, 'lng'=>6.0167 ],
        'kahler' => [ 'name'=>'Kahler', 'lux'=>'Kalen', 'municipality'=>'Garnich', 'canton'=>'Capellen', 'lat'=>49.6300, 'lng'=>5.9167 ],
        'kalborn' => [ 'name'=>'Kalborn', 'lux'=>'Kaalber', 'municipality'=>'Clervaux', 'canton'=>'Clervaux', 'lat'=>50.1000, 'lng'=>6.1167 ],
        'kalborn-moulin' => [ 'name'=>'Kalborn-Moulin', 'lux'=>'Kaalber Millen', 'municipality'=>'Clervaux', 'canton'=>'Clervaux', 'lat'=>50.1111, 'lng'=>6.1167 ],
        'kalchesbreck' => [ 'name'=>'Kalchesbréck', 'lux'=>'Kalchesbréck', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6230, 'lng'=>6.1750 ],
        'kalkesbach-berdorf' => [ 'name'=>'Kalkesbach (Berdorf)', 'lux'=>'Kalkesbaach', 'municipality'=>'Berdorf', 'canton'=>'Echternach', 'lat'=>49.8333, 'lng'=>6.3333 ],
        'kalkesbach-consdorf' => [ 'name'=>'Kalkesbach (Consdorf)', 'lux'=>'Kalkesbaach', 'municipality'=>'Consdorf', 'canton'=>'Echternach', 'lat'=>49.7667, 'lng'=>6.3333 ],
        'kapenacker' => [ 'name'=>'Kapenacker', 'lux'=>'Kapenacker', 'municipality'=>'Wormeldange', 'canton'=>'Grevenmacher', 'lat'=>49.6410, 'lng'=>6.3860 ],
        'kapweiler' => [ 'name'=>'Kapweiler', 'lux'=>'Kapweiler', 'municipality'=>'Saeul', 'canton'=>'Redange', 'lat'=>49.7210, 'lng'=>5.9550 ],
        'kaundorf' => [ 'name'=>'Kaundorf', 'lux'=>'Kauneref', 'municipality'=>'Lac de la Haute-Sûre', 'canton'=>'Wiltz', 'lat'=>49.9167, 'lng'=>5.9000 ],
        'kautenbach' => [ 'name'=>'Kautenbach', 'lux'=>'Kautenbach', 'municipality'=>'Kiischpelt', 'canton'=>'Wiltz', 'lat'=>49.9500, 'lng'=>6.0167 ],
        'kayl' => [ 'name'=>'Kayl', 'lux'=>'Keel', 'municipality'=>'Kayl', 'canton'=>'Esch/Alzette', 'lat'=>49.4833, 'lng'=>6.0333 ],
        'kehlen' => [ 'name'=>'Kehlen', 'lux'=>'Keehlen', 'municipality'=>'Kehlen', 'canton'=>'Capellen', 'lat'=>49.6667, 'lng'=>6.0333 ],
        'kehmen' => [ 'name'=>'Kehmen', 'lux'=>'Kiemen', 'municipality'=>'Bourscheid', 'canton'=>'Diekirch', 'lat'=>49.8833, 'lng'=>6.0333 ],
        'keispelt' => [ 'name'=>'Keispelt', 'lux'=>'Keespelt', 'municipality'=>'Kehlen', 'canton'=>'Capellen', 'lat'=>49.6910, 'lng'=>6.0680 ],
        'keiwelbach' => [ 'name'=>'Keiwelbach', 'lux'=>'Keiwelbaach', 'municipality'=>'Beaufort', 'canton'=>'Echternach', 'lat'=>49.8510, 'lng'=>6.2840 ],
        'kirchberg' => [ 'name'=>'Kirchberg', 'lux'=>'Kierchbierg', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6300, 'lng'=>6.1600 ],
        'kirelshof' => [ 'name'=>'Kirelshof', 'lux'=>'Kirelshaff', 'municipality'=>'Lac de la Haute-Sûre', 'canton'=>'Wiltz', 'lat'=>49.9320, 'lng'=>5.8650 ],
        'kleemuhle' => [ 'name'=>'Kleemühle', 'lux'=>'Kleemillen', 'municipality'=>'Troisvierges', 'canton'=>'Clervaux', 'lat'=>50.1167, 'lng'=>6.0000 ],
        'kleinbettingen' => [ 'name'=>'Kleinbettingen', 'lux'=>'Klengbetten', 'municipality'=>'Steinfort', 'canton'=>'Capellen', 'lat'=>49.6439, 'lng'=>5.9144 ],
        'klingelscheuer' => [ 'name'=>'Klingelscheuer', 'lux'=>'Klengelscheier', 'municipality'=>'Junglinster', 'canton'=>'Grevenmacher', 'lat'=>49.7000, 'lng'=>6.1833 ],
        'knaphoscheid' => [ 'name'=>'Knaphoscheid', 'lux'=>'Knapphouschent', 'municipality'=>'Wiltz', 'canton'=>'Wiltz', 'lat'=>50.0100, 'lng'=>5.9600 ],
        'kobenbour' => [ 'name'=>'Kobenbour', 'lux'=>'Koubebuert', 'municipality'=>'Bech', 'canton'=>'Echternach', 'lat'=>49.7500, 'lng'=>6.2833 ],
        'kockelscheuer' => [ 'name'=>'Kockelscheuer', 'lux'=>'Kockelscheier', 'municipality'=>'Roeser', 'canton'=>'Luxembourg', 'lat'=>49.5667, 'lng'=>6.1167 ],
        'koedange' => [ 'name'=>'Koedange', 'lux'=>'Kiedeng', 'municipality'=>'Fischbach', 'canton'=>'Mersch', 'lat'=>49.7667, 'lng'=>6.1833 ],
        'koerich' => [ 'name'=>'Koerich', 'lux'=>'Käerch', 'municipality'=>'Koerich', 'canton'=>'Capellen', 'lat'=>49.6667, 'lng'=>5.9500 ],
        'koetschette' => [ 'name'=>'Koetschette', 'lux'=>'Kietscht', 'municipality'=>'Rambrouch', 'canton'=>'Redange', 'lat'=>49.8583, 'lng'=>5.8306 ],
        'kopstal' => [ 'name'=>'Kopstal', 'lux'=>'Koplescht', 'municipality'=>'Kopstal', 'canton'=>'Capellen', 'lat'=>49.6667, 'lng'=>6.0667 ],
        'kuborn' => [ 'name'=>'Kuborn', 'lux'=>'Kuber', 'municipality'=>'Wahl', 'canton'=>'Redange', 'lat'=>49.8833, 'lng'=>5.9167 ],
        'kuelbecherhaff' => [ 'name'=>'Kuelbecherhaff', 'lux'=>'Kuelbecherhaff', 'municipality'=>'Helperknapp', 'canton'=>'Mersch', 'lat'=>49.7333, 'lng'=>6.0167 ],
        'lamadelaine' => [ 'name'=>'Lamadelaine', 'lux'=>'Rolleng', 'municipality'=>'Pétange', 'canton'=>'Esch/Alzette', 'lat'=>49.5461, 'lng'=>5.8614 ],
        'landscheid' => [ 'name'=>'Landscheid', 'lux'=>'Landscheid', 'municipality'=>'Tandel', 'canton'=>'Vianden', 'lat'=>49.8833, 'lng'=>6.1333 ],
        'lannen' => [ 'name'=>'Lannen', 'lux'=>'Lannen', 'municipality'=>'Redange/Attert', 'canton'=>'Redange', 'lat'=>49.7833, 'lng'=>5.8500 ],
        'larochette' => [ 'name'=>'Larochette', 'lux'=>'Fiels', 'municipality'=>'Larochette', 'canton'=>'Mersch', 'lat'=>49.7844, 'lng'=>6.2186 ],
        'lasauvage' => [ 'name'=>'Lasauvage', 'lux'=>'Lasauvage', 'municipality'=>'Differdange', 'canton'=>'Esch/Alzette', 'lat'=>49.5128, 'lng'=>5.8367 ],
        'lausdorn' => [ 'name'=>'Lausdorn', 'lux'=>'Lausdorn', 'municipality'=>'Weiswampach', 'canton'=>'Clervaux', 'lat'=>50.1167, 'lng'=>6.0833 ],
        'leesbach' => [ 'name'=>'Leesbach', 'lux'=>'Leesbach', 'municipality'=>'Habscht', 'canton'=>'Capellen', 'lat'=>49.7110, 'lng'=>5.9230 ],
        'lehrhof' => [ 'name'=>'Lehrhof', 'lux'=>'Léierhaff', 'municipality'=>'Grosbous-Wal', 'canton'=>'Redange', 'lat'=>49.8333, 'lng'=>5.9167 ],
        'leithum' => [ 'name'=>'Leithum', 'lux'=>'Letum', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.1333, 'lng'=>6.1000 ],
        'lellig' => [ 'name'=>'Lellig', 'lux'=>'Lelléig', 'municipality'=>'Manternach', 'canton'=>'Grevenmacher', 'lat'=>49.7167, 'lng'=>6.4333 ],
        'lellingen' => [ 'name'=>'Lellingen', 'lux'=>'Lellgen', 'municipality'=>'Kiischpelt', 'canton'=>'Wiltz', 'lat'=>49.9856, 'lng'=>6.0125 ],
        'lenningen' => [ 'name'=>'Lenningen', 'lux'=>'Lenneng', 'municipality'=>'Lenningen', 'canton'=>'Remich', 'lat'=>49.6000, 'lng'=>6.3667 ],
        'lentzweiler' => [ 'name'=>'Lentzweiler', 'lux'=>'Lëntswéiler', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0167, 'lng'=>5.9500 ],
        'leudelange' => [ 'name'=>'Leudelange', 'lux'=>'Leideleng', 'municipality'=>'Leudelange', 'canton'=>'Esch/Alzette', 'lat'=>49.5667, 'lng'=>6.0667 ],
        'levelange' => [ 'name'=>'Levelange', 'lux'=>'Liewel', 'municipality'=>'Beckerich', 'canton'=>'Redange', 'lat'=>49.7167, 'lng'=>5.8333 ],
        'liefrange' => [ 'name'=>'Liefrange', 'lux'=>'Léifreg', 'municipality'=>'Lac de la Haute-Sûre', 'canton'=>'Wiltz', 'lat'=>49.9000, 'lng'=>5.8667 ],
        'lieler' => [ 'name'=>'Lieler', 'lux'=>'Liler', 'municipality'=>'Clervaux', 'canton'=>'Clervaux', 'lat'=>50.1264, 'lng'=>6.1114 ],
        'lilien' => [ 'name'=>'Lilien', 'lux'=>'Liljen', 'municipality'=>'Rosport-Mompach', 'canton'=>'Echternach', 'lat'=>49.7667, 'lng'=>6.4167 ],
        'limpach' => [ 'name'=>'Limpach', 'lux'=>'Lampech', 'municipality'=>'Reckange-sur-Mess', 'canton'=>'Esch/Alzette', 'lat'=>49.5500, 'lng'=>6.0000 ],
        'limpertsberg' => [ 'name'=>'Limpertsberg', 'lux'=>'Lampertsbierg', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6167, 'lng'=>6.1167 ],
        'linger' => [ 'name'=>'Linger', 'lux'=>'Lengert', 'municipality'=>'Käerjeng', 'canton'=>'Capellen', 'lat'=>49.5667, 'lng'=>5.8833 ],
        'lintgen' => [ 'name'=>'Lintgen', 'lux'=>'Lëntgen', 'municipality'=>'Lintgen', 'canton'=>'Mersch', 'lat'=>49.7167, 'lng'=>6.1333 ],
        'lipperscheid' => [ 'name'=>'Lipperscheid', 'lux'=>'Lëpschent', 'municipality'=>'Bourscheid', 'canton'=>'Diekirch', 'lat'=>49.9167, 'lng'=>6.0833 ],
        'livange' => [ 'name'=>'Livange', 'lux'=>'Léiweng', 'municipality'=>'Roeser', 'canton'=>'Luxembourg', 'lat'=>49.5333, 'lng'=>6.1167 ],
        'longsdorf' => [ 'name'=>'Longsdorf', 'lux'=>'Longsdref', 'municipality'=>'Tandel', 'canton'=>'Vianden', 'lat'=>49.8833, 'lng'=>6.2167 ],
        'lorentzweiler' => [ 'name'=>'Lorentzweiler', 'lux'=>'Luerenzweiler', 'municipality'=>'Lorentzweiler', 'canton'=>'Mersch', 'lat'=>49.7000, 'lng'=>6.1333 ],
        'lullange' => [ 'name'=>'Lullange', 'lux'=>'Lulléng', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0167, 'lng'=>5.9333 ],
        'lultzhausen' => [ 'name'=>'Lultzhausen', 'lux'=>'Lëlz', 'municipality'=>'Lac de la Haute-Sûre', 'canton'=>'Wiltz', 'lat'=>49.9000, 'lng'=>5.8833 ],
        'luxembourg' => [ 'name'=>'Luxembourg', 'lux'=>'Lëtzebuerg', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6111, 'lng'=>6.1333 ],
        'machtum' => [ 'name'=>'Machtum', 'lux'=>'Maacher', 'municipality'=>'Wormeldange', 'canton'=>'Grevenmacher', 'lat'=>49.6500, 'lng'=>6.4333 ],
        'mamer' => [ 'name'=>'Mamer', 'lux'=>'Mamer', 'municipality'=>'Mamer', 'canton'=>'Capellen', 'lat'=>49.6333, 'lng'=>6.0167 ],
        'manternach' => [ 'name'=>'Manternach', 'lux'=>'Manternach', 'municipality'=>'Manternach', 'canton'=>'Grevenmacher', 'lat'=>49.7000, 'lng'=>6.4333 ],
        'marienthal' => [ 'name'=>'Marienthal', 'lux'=>'Mariendall', 'municipality'=>'Helperknapp', 'canton'=>'Mersch', 'lat'=>49.7167, 'lng'=>6.0667 ],
        'marnach' => [ 'name'=>'Marnach', 'lux'=>'Maarnach', 'municipality'=>'Clervaux', 'canton'=>'Clervaux', 'lat'=>50.0500, 'lng'=>6.0667 ],
        'marscherwald' => [ 'name'=>'Marscherwald', 'lux'=>'Marscherwald', 'municipality'=>'Bech', 'canton'=>'Echternach', 'lat'=>49.7667, 'lng'=>6.2667 ],
        'masseler' => [ 'name'=>'Masseler', 'lux'=>'Masseler', 'municipality'=>'Goesdorf', 'canton'=>'Wiltz', 'lat'=>49.9167, 'lng'=>6.0167 ],
        'maulusmuhle' => [ 'name'=>'Maulusmühle', 'lux'=>'Maulusmillen', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0833, 'lng'=>6.0333 ],
        'mecher-clervaux' => [ 'name'=>'Mecher (Clervaux)', 'lux'=>'Mecher', 'municipality'=>'Clervaux', 'canton'=>'Clervaux', 'lat'=>50.0833, 'lng'=>6.0167 ],
        'mecher-l-d-h-s' => [ 'name'=>'Mecher (L.d.H.S.)', 'lux'=>'Mecher', 'municipality'=>'Lac de la Haute-Sûre', 'canton'=>'Wiltz', 'lat'=>49.9167, 'lng'=>5.8667 ],
        'medernach' => [ 'name'=>'Medernach', 'lux'=>'Miedernach', 'municipality'=>'Vallée de l\'Ernz', 'canton'=>'Diekirch', 'lat'=>49.8000, 'lng'=>6.2167 ],
        'medingen' => [ 'name'=>'Medingen', 'lux'=>'Méideng', 'municipality'=>'Contern', 'canton'=>'Luxembourg', 'lat'=>49.5667, 'lng'=>6.2500 ],
        'meispelt' => [ 'name'=>'Meispelt', 'lux'=>'Meispelt', 'municipality'=>'Kehlen', 'canton'=>'Capellen', 'lat'=>49.6917, 'lng'=>6.0667 ],
        'mensdorf' => [ 'name'=>'Mensdorf', 'lux'=>'Menster', 'municipality'=>'Betzdorf', 'canton'=>'Grevenmacher', 'lat'=>49.6500, 'lng'=>6.3000 ],
        'merkholtz' => [ 'name'=>'Merkholtz', 'lux'=>'Mäerzelt', 'municipality'=>'Kiischpelt', 'canton'=>'Wiltz', 'lat'=>49.9500, 'lng'=>5.9833 ],
        'merl' => [ 'name'=>'Merl', 'lux'=>'Mäerl', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6000, 'lng'=>6.1000 ],
        'mersch' => [ 'name'=>'Mersch', 'lux'=>'Miersch', 'municipality'=>'Mersch', 'canton'=>'Mersch', 'lat'=>49.7500, 'lng'=>6.1000 ],
        'merscheid-esch-sure' => [ 'name'=>'Merscheid (Esch/Sûre)', 'lux'=>'Mäerzeg', 'municipality'=>'Esch-sur-Sûre', 'canton'=>'Wiltz', 'lat'=>49.8720, 'lng'=>5.9690 ],
        'merscheid-p-h' => [ 'name'=>'Merscheid (P.H.)', 'lux'=>'Mäerzeg', 'municipality'=>'Parc Hosingen', 'canton'=>'Clervaux', 'lat'=>49.9833, 'lng'=>6.0500 ],
        'mertert' => [ 'name'=>'Mertert', 'lux'=>'Mäertert', 'municipality'=>'Mertert', 'canton'=>'Grevenmacher', 'lat'=>49.7000, 'lng'=>6.4833 ],
        'mertzig' => [ 'name'=>'Mertzig', 'lux'=>'Mäerzeg', 'municipality'=>'Mertzig', 'canton'=>'Diekirch', 'lat'=>49.8333, 'lng'=>6.0000 ],
        'meysembourg' => [ 'name'=>'Meysembourg', 'lux'=>'Meisembuerg', 'municipality'=>'Larochette', 'canton'=>'Mersch', 'lat'=>49.7667, 'lng'=>6.1833 ],
        'michelau' => [ 'name'=>'Michelau', 'lux'=>'Michelau', 'municipality'=>'Bourscheid', 'canton'=>'Diekirch', 'lat'=>49.9000, 'lng'=>6.1000 ],
        'michelbouch' => [ 'name'=>'Michelbouch', 'lux'=>'Méchelbuch', 'municipality'=>'Vichten', 'canton'=>'Redange', 'lat'=>49.8167, 'lng'=>6.0167 ],
        'michelshof' => [ 'name'=>'Michelshof', 'lux'=>'Michelshaff', 'municipality'=>'Bech', 'canton'=>'Echternach', 'lat'=>49.7833, 'lng'=>6.3167 ],
        'moersdorf' => [ 'name'=>'Moersdorf', 'lux'=>'Méischdref', 'municipality'=>'Rosport-Mompach', 'canton'=>'Echternach', 'lat'=>49.7333, 'lng'=>6.5000 ],
        'moesdorf' => [ 'name'=>'Moesdorf', 'lux'=>'Méisdref', 'municipality'=>'Mersch', 'canton'=>'Mersch', 'lat'=>49.7333, 'lng'=>6.1167 ],
        'moestroff' => [ 'name'=>'Moestroff', 'lux'=>'Méischtref', 'municipality'=>'Bettendorf', 'canton'=>'Diekirch', 'lat'=>49.8667, 'lng'=>6.2333 ],
        'mompach' => [ 'name'=>'Mompach', 'lux'=>'Mompech', 'municipality'=>'Rosport-Mompach', 'canton'=>'Echternach', 'lat'=>49.7461, 'lng'=>6.4631 ],
        'mondercange' => [ 'name'=>'Mondercange', 'lux'=>'Monnerech', 'municipality'=>'Mondercange', 'canton'=>'Esch/Alzette', 'lat'=>49.5317, 'lng'=>5.9889 ],
        'mondorf-les-bains' => [ 'name'=>'Mondorf-les-Bains', 'lux'=>'Munneref', 'municipality'=>'Mondorf-les-Bains', 'canton'=>'Remich', 'lat'=>49.5064, 'lng'=>6.2731 ],
        'moutfort' => [ 'name'=>'Moutfort', 'lux'=>'Mutfert', 'municipality'=>'Contern', 'canton'=>'Luxembourg', 'lat'=>49.5881, 'lng'=>6.2553 ],
        'muhlenbach' => [ 'name'=>'Mühlenbach', 'lux'=>'Millebaach', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6260, 'lng'=>6.1210 ],
        'mullendorf' => [ 'name'=>'Mullendorf', 'lux'=>'Mullenduerf', 'municipality'=>'Steinsel', 'canton'=>'Luxembourg', 'lat'=>49.6761, 'lng'=>6.1306 ],
        'mullerthal' => [ 'name'=>'Mullerthal', 'lux'=>'Mëllerdall', 'municipality'=>'Waldbillig', 'canton'=>'Echternach', 'lat'=>49.7908, 'lng'=>6.3072 ],
        'munsbach' => [ 'name'=>'Munsbach', 'lux'=>'Münsbech', 'municipality'=>'Schuttrange', 'canton'=>'Luxembourg', 'lat'=>49.6361, 'lng'=>6.2656 ],
        'munschecker' => [ 'name'=>'Münschecker', 'lux'=>'Mënsbecher', 'municipality'=>'Macher', 'canton'=>'Grevenmacher', 'lat'=>49.7042, 'lng'=>6.4103 ],
        'munshausen' => [ 'name'=>'Munshausen', 'lux'=>'Munzen', 'municipality'=>'Clervaux', 'canton'=>'Clervaux', 'lat'=>50.0350, 'lng'=>6.0375 ],
        'nachtmanderscheid' => [ 'name'=>'Nachtmanderscheid', 'lux'=>'Nuechtmanderschent', 'municipality'=>'Putscheid', 'canton'=>'Vianden', 'lat'=>49.9333, 'lng'=>6.1333 ],
        'nagem' => [ 'name'=>'Nagem', 'lux'=>'Nojem', 'municipality'=>'Redange/Attert', 'canton'=>'Redange', 'lat'=>49.7847, 'lng'=>5.8503 ],
        'neidhausen' => [ 'name'=>'Neidhausen', 'lux'=>'Neidhausen', 'municipality'=>'Parc Hosingen', 'canton'=>'Clervaux', 'lat'=>50.0167, 'lng'=>6.0667 ],
        'neudorf' => [ 'name'=>'Neudorf', 'lux'=>'Neiduerf', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6200, 'lng'=>6.1550 ],
        'neuhaeusgen' => [ 'name'=>'Neuhaeusgen', 'lux'=>'Neihäusgen', 'municipality'=>'Schuttrange', 'canton'=>'Luxembourg', 'lat'=>49.6210, 'lng'=>6.2520 ],
        'neunhausen' => [ 'name'=>'Neunhausen', 'lux'=>'Néngsen', 'municipality'=>'Esch-sur-Sûre', 'canton'=>'Wiltz', 'lat'=>49.8769, 'lng'=>5.8858 ],
        'niederanven' => [ 'name'=>'Niederanven', 'lux'=>'Nidderanwen', 'municipality'=>'Niederanven', 'canton'=>'Luxembourg', 'lat'=>49.6469, 'lng'=>6.2625 ],
        'niederdonven' => [ 'name'=>'Niederdonven', 'lux'=>'Nidderdonwen', 'municipality'=>'Flaxweiler', 'canton'=>'Grevenmacher', 'lat'=>49.6311, 'lng'=>6.4022 ],
        'niederfeulen' => [ 'name'=>'Niederfeulen', 'lux'=>'Nidderfeelen', 'municipality'=>'Feulen', 'canton'=>'Diekirch', 'lat'=>49.8510, 'lng'=>6.0460 ],
        'niederglabach' => [ 'name'=>'Niederglabach', 'lux'=>'Nidderglabach', 'municipality'=>'Nommern', 'canton'=>'Mersch', 'lat'=>49.7840, 'lng'=>6.1660 ],
        'niederkorn' => [ 'name'=>'Niederkorn', 'lux'=>'Nidderkuer', 'municipality'=>'Differdange', 'canton'=>'Esch/Alzette', 'lat'=>49.5361, 'lng'=>5.8911 ],
        'niederpallen' => [ 'name'=>'Niederpallen', 'lux'=>'Nidderpallen', 'municipality'=>'Redange/Attert', 'canton'=>'Redange', 'lat'=>49.7511, 'lng'=>5.9114 ],
        'niederwampach' => [ 'name'=>'Niederwampach', 'lux'=>'Nidderwampech', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0078, 'lng'=>5.8422 ],
        'niesenthal' => [ 'name'=>'Niesenthal', 'lux'=>'Niesenthal', 'municipality'=>'Tandel', 'canton'=>'Vianden', 'lat'=>49.9070, 'lng'=>6.1750 ],
        'nocher' => [ 'name'=>'Nocher', 'lux'=>'Nocher', 'municipality'=>'Goesdorf', 'canton'=>'Wiltz', 'lat'=>49.9500, 'lng'=>5.9667 ],
        'nocher-route' => [ 'name'=>'Nocher-Route', 'lux'=>'Nocher-Strooss', 'municipality'=>'Goesdorf', 'canton'=>'Wiltz', 'lat'=>49.9450, 'lng'=>5.9610 ],
        'noerdange' => [ 'name'=>'Noerdange', 'lux'=>'Näerdeng', 'municipality'=>'Beckerich', 'canton'=>'Redange', 'lat'=>49.7431, 'lng'=>5.9267 ],
        'noertrange' => [ 'name'=>'Noertrange', 'lux'=>'Näertreg', 'municipality'=>'Winseler', 'canton'=>'Wiltz', 'lat'=>49.9810, 'lng'=>5.9220 ],
        'noertzange' => [ 'name'=>'Noertzange', 'lux'=>'Näerzeng', 'municipality'=>'Bettembourg', 'canton'=>'Esch/Alzette', 'lat'=>49.5100, 'lng'=>6.0560 ],
        'nommern' => [ 'name'=>'Nommern', 'lux'=>'Noumer', 'municipality'=>'Nommern', 'canton'=>'Mersch', 'lat'=>49.7644, 'lng'=>6.1739 ],
        'nospelt' => [ 'name'=>'Nospelt', 'lux'=>'Nouspelt', 'municipality'=>'Kehlen', 'canton'=>'Capellen', 'lat'=>49.6739, 'lng'=>6.0083 ],
        'nothum' => [ 'name'=>'Nothum', 'lux'=>'Noutem', 'municipality'=>'Lac de la Haute-Sûre', 'canton'=>'Wiltz', 'lat'=>49.9372, 'lng'=>5.8814 ],
        'oberanven' => [ 'name'=>'Oberanven', 'lux'=>'Ieweschtanwen', 'municipality'=>'Niederanven', 'canton'=>'Luxembourg', 'lat'=>49.6580, 'lng'=>6.2550 ],
        'oberdonven' => [ 'name'=>'Oberdonven', 'lux'=>'Ieweschtdonwen', 'municipality'=>'Flaxweiler', 'canton'=>'Grevenmacher', 'lat'=>49.6480, 'lng'=>6.4020 ],
        'oberfeulen' => [ 'name'=>'Oberfeulen', 'lux'=>'Ieweschtfeelen', 'municipality'=>'Feulen', 'canton'=>'Diekirch', 'lat'=>49.8560, 'lng'=>6.0280 ],
        'oberglabach' => [ 'name'=>'Oberglabach', 'lux'=>'Ieweschtglabach', 'municipality'=>'Nommern', 'canton'=>'Mersch', 'lat'=>49.7920, 'lng'=>6.1680 ],
        'oberkorn' => [ 'name'=>'Oberkorn', 'lux'=>'Uewerkorn', 'municipality'=>'Differdange', 'canton'=>'Esch/Alzette', 'lat'=>49.5140, 'lng'=>5.8920 ],
        'oberpallen' => [ 'name'=>'Oberpallen', 'lux'=>'Uewerpallen', 'municipality'=>'Beckerich', 'canton'=>'Redange', 'lat'=>49.7820, 'lng'=>5.8390 ],
        'oberschlinder' => [ 'name'=>'Oberschlinder', 'lux'=>'Oberschlinder', 'municipality'=>'Parc Hosingen', 'canton'=>'Clervaux', 'lat'=>49.9510, 'lng'=>6.0620 ],
        'oberwampach' => [ 'name'=>'Oberwampach', 'lux'=>'Ieweschtwampech', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0150, 'lng'=>5.8560 ],
        'oetrange' => [ 'name'=>'Oetrange', 'lux'=>'Éitreg', 'municipality'=>'Contern', 'canton'=>'Luxembourg', 'lat'=>49.6010, 'lng'=>6.2580 ],
        'olingen' => [ 'name'=>'Olingen', 'lux'=>'Olyng', 'municipality'=>'Betzdorf', 'canton'=>'Grevenmacher', 'lat'=>49.6790, 'lng'=>6.3150 ],
        'olm' => [ 'name'=>'Olm', 'lux'=>'Ollem', 'municipality'=>'Kehlen', 'canton'=>'Capellen', 'lat'=>49.6510, 'lng'=>5.9960 ],
        'openthalt' => [ 'name'=>'Openthalt', 'lux'=>'Openthalt', 'municipality'=>'Helperknapp', 'canton'=>'Mersch', 'lat'=>49.7610, 'lng'=>6.0550 ],
        'ospern' => [ 'name'=>'Ospern', 'lux'=>'Osper', 'municipality'=>'Redange/Attert', 'canton'=>'Redange', 'lat'=>49.7840, 'lng'=>5.9010 ],
        'osweiler' => [ 'name'=>'Osweiler', 'lux'=>'Osweiler', 'municipality'=>'Rosport-Mompach', 'canton'=>'Echternach', 'lat'=>49.7850, 'lng'=>6.4380 ],
        'peppange' => [ 'name'=>'Peppange', 'lux'=>'Peppeng', 'municipality'=>'Roeser', 'canton'=>'Luxembourg', 'lat'=>49.5250, 'lng'=>6.1300 ],
        'perle' => [ 'name'=>'Perlé', 'lux'=>'Pärel', 'municipality'=>'Rambrouch', 'canton'=>'Redange', 'lat'=>49.8100, 'lng'=>5.7660 ],
        'petange' => [ 'name'=>'Pétange', 'lux'=>'Péiteng', 'municipality'=>'Pétange', 'canton'=>'Esch/Alzette', 'lat'=>49.5564, 'lng'=>5.8769 ],
        'petit-nobressart' => [ 'name'=>'Petit-Nobressart', 'lux'=>'Kleng-Elchert', 'municipality'=>'Ell', 'canton'=>'Redange', 'lat'=>49.7750, 'lng'=>5.7950 ],
        'pettingen' => [ 'name'=>'Pettingen', 'lux'=>'Pëtteng', 'municipality'=>'Mersch', 'canton'=>'Mersch', 'lat'=>49.7700, 'lng'=>6.1080 ],
        'pfaffenthal' => [ 'name'=>'Pfaffenthal', 'lux'=>'Pafendall', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6160, 'lng'=>6.1320 ],
        'pintsch' => [ 'name'=>'Pintsch', 'lux'=>'Pënsch', 'municipality'=>'Kiischpelt', 'canton'=>'Wiltz', 'lat'=>49.9928, 'lng'=>6.0111 ],
        'pissange' => [ 'name'=>'Pissange', 'lux'=>'Pisseng', 'municipality'=>'Reckange-sur-Mess', 'canton'=>'Esch/Alzette', 'lat'=>49.5530, 'lng'=>6.0090 ],
        'platen' => [ 'name'=>'Platen', 'lux'=>'Platen', 'municipality'=>'Préizerdaul', 'canton'=>'Redange', 'lat'=>49.7900, 'lng'=>5.9320 ],
        'pommerloch' => [ 'name'=>'Pommerloch', 'lux'=>'Pommerlach', 'municipality'=>'Winseler', 'canton'=>'Wiltz', 'lat'=>49.9610, 'lng'=>5.8640 ],
        'pontpierre' => [ 'name'=>'Pontpierre', 'lux'=>'Steebréck', 'municipality'=>'Mondercange', 'canton'=>'Esch/Alzette', 'lat'=>49.5350, 'lng'=>6.0300 ],
        'pratz' => [ 'name'=>'Pratz', 'lux'=>'Proz', 'municipality'=>'Préizerdaul', 'canton'=>'Redange', 'lat'=>49.7950, 'lng'=>5.9250 ],
        'prettingen' => [ 'name'=>'Prettingen', 'lux'=>'Preiteng', 'municipality'=>'Lintgen', 'canton'=>'Mersch', 'lat'=>49.7280, 'lng'=>6.1360 ],
        'pulvermuhl' => [ 'name'=>'Pulvermühl', 'lux'=>'Polfermillen', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6100, 'lng'=>6.1480 ],
        'putscheid' => [ 'name'=>'Putscheid', 'lux'=>'Pëtscht', 'municipality'=>'Putscheid', 'canton'=>'Vianden', 'lat'=>49.9590, 'lng'=>6.1410 ],
        'rambrouch' => [ 'name'=>'Rambrouch', 'lux'=>'Rammerech', 'municipality'=>'Rambrouch', 'canton'=>'Redange', 'lat'=>49.8290, 'lng'=>5.8500 ],
        'rameldange' => [ 'name'=>'Rameldange', 'lux'=>'Rammeldeng', 'municipality'=>'Niederanven', 'canton'=>'Luxembourg', 'lat'=>49.6600, 'lng'=>6.2370 ],
        'reckange-mersch' => [ 'name'=>'Reckange (Mersch)', 'lux'=>'Recken', 'municipality'=>'Mersch', 'canton'=>'Mersch', 'lat'=>49.7430, 'lng'=>6.0840 ],
        'reckange-sur-mess' => [ 'name'=>'Reckange-sur-Mess', 'lux'=>'Recken op der Mess', 'municipality'=>'Reckange-sur-Mess', 'canton'=>'Esch/Alzette', 'lat'=>49.5610, 'lng'=>6.0080 ],
        'reckingerhof' => [ 'name'=>'Reckingerhof', 'lux'=>'Reckingerhaff', 'municipality'=>'Dalheim', 'canton'=>'Remich', 'lat'=>49.5480, 'lng'=>6.2420 ],
        'redange-attert' => [ 'name'=>'Redange/Attert', 'lux'=>'Réiden op der Atert', 'municipality'=>'Redange/Attert', 'canton'=>'Redange', 'lat'=>49.7650, 'lng'=>5.8890 ],
        'reichlange' => [ 'name'=>'Reichlange', 'lux'=>'Räichleng', 'municipality'=>'Redange/Attert', 'canton'=>'Redange', 'lat'=>49.7750, 'lng'=>5.9220 ],
        'reimberg' => [ 'name'=>'Reimberg', 'lux'=>'Rëmmerech', 'municipality'=>'Préizerdaul', 'canton'=>'Redange', 'lat'=>49.8050, 'lng'=>5.9390 ],
        'reisdorf' => [ 'name'=>'Reisdorf', 'lux'=>'Reisduerf', 'municipality'=>'Reisdorf', 'canton'=>'Diekirch', 'lat'=>49.8680, 'lng'=>6.2670 ],
        'remerschen' => [ 'name'=>'Remerschen', 'lux'=>'Rëmerschen', 'municipality'=>'Schengen', 'canton'=>'Remich', 'lat'=>49.4850, 'lng'=>6.3510 ],
        'remich' => [ 'name'=>'Remich', 'lux'=>'Réimech', 'municipality'=>'Remich', 'canton'=>'Remich', 'lat'=>49.5440, 'lng'=>6.3670 ],
        'reuland' => [ 'name'=>'Reuland', 'lux'=>'Reiland', 'municipality'=>'Heffingen', 'canton'=>'Mersch', 'lat'=>49.7660, 'lng'=>6.2160 ],
        'reuler' => [ 'name'=>'Reuler', 'lux'=>'Reiler', 'municipality'=>'Clervaux', 'canton'=>'Clervaux', 'lat'=>50.0590, 'lng'=>6.0460 ],
        'riesenhof' => [ 'name'=>'Riesenhof', 'lux'=>'Riesenhof', 'municipality'=>'Rambrouch', 'canton'=>'Redange', 'lat'=>49.8450, 'lng'=>5.7650 ],
        'rindschleiden' => [ 'name'=>'Rindschleiden', 'lux'=>'Randschelt', 'municipality'=>'Grosbous-Wal', 'canton'=>'Redange', 'lat'=>49.8510, 'lng'=>5.8970 ],
        'ringel' => [ 'name'=>'Ringel', 'lux'=>'Ringel', 'municipality'=>'Esch-sur-Sûre', 'canton'=>'Wiltz', 'lat'=>49.9070, 'lng'=>6.0120 ],
        'rippig' => [ 'name'=>'Rippig', 'lux'=>'Rippeg', 'municipality'=>'Bech', 'canton'=>'Echternach', 'lat'=>49.7400, 'lng'=>6.3050 ],
        'rippweiler' => [ 'name'=>'Rippweiler', 'lux'=>'Rippweiler', 'municipality'=>'Useldange', 'canton'=>'Redange', 'lat'=>49.7480, 'lng'=>5.9560 ],
        'rodange' => [ 'name'=>'Rodange', 'lux'=>'Rodange', 'municipality'=>'Pétange', 'canton'=>'Esch/Alzette', 'lat'=>49.5550, 'lng'=>5.8410 ],
        'rodenbourg' => [ 'name'=>'Rodenbourg', 'lux'=>'Roudemer', 'municipality'=>'Junglinster', 'canton'=>'Grevenmacher', 'lat'=>49.6880, 'lng'=>6.2730 ],
        'roder' => [ 'name'=>'Roder', 'lux'=>'Roder', 'municipality'=>'Clervaux', 'canton'=>'Clervaux', 'lat'=>50.0560, 'lng'=>6.0880 ],
        'rodershausen' => [ 'name'=>'Rodershausen', 'lux'=>'Rodershausen', 'municipality'=>'Parc Hosingen', 'canton'=>'Clervaux', 'lat'=>50.0070, 'lng'=>6.1360 ],
        'roedgen' => [ 'name'=>'Roedgen', 'lux'=>'Riedgen', 'municipality'=>'Reckange-sur-Mess', 'canton'=>'Esch/Alzette', 'lat'=>49.5660, 'lng'=>6.0430 ],
        'roedt' => [ 'name'=>'Roedt', 'lux'=>'Réit', 'municipality'=>'Waldbredimus', 'canton'=>'Remich', 'lat'=>49.5600, 'lng'=>6.2750 ],
        'roeser' => [ 'name'=>'Roeser', 'lux'=>'Réiser', 'municipality'=>'Roeser', 'canton'=>'Luxembourg', 'lat'=>49.5390, 'lng'=>6.1470 ],
        'rolling' => [ 'name'=>'Rolling', 'lux'=>'Rolling', 'municipality'=>'Bous-Waldbredimus', 'canton'=>'Remich', 'lat'=>49.5450, 'lng'=>6.3150 ],
        'rollingen' => [ 'name'=>'Rollingen', 'lux'=>'Rolleng', 'municipality'=>'Mersch', 'canton'=>'Mersch', 'lat'=>49.7490, 'lng'=>6.1130 ],
        'rollingergrund' => [ 'name'=>'Rollingergrund', 'lux'=>'Rolléngergrund', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6200, 'lng'=>6.1050 ],
        'rombach-martelange' => [ 'name'=>'Rombach-Martelange', 'lux'=>'Roumbach', 'municipality'=>'Rambrouch', 'canton'=>'Redange', 'lat'=>49.8310, 'lng'=>5.7480 ],
        'roodt-ell' => [ 'name'=>'Roodt (Ell)', 'lux'=>'Rued', 'municipality'=>'Ell', 'canton'=>'Redange', 'lat'=>49.7910, 'lng'=>5.8190 ],
        'roodt-sur-syre' => [ 'name'=>'Roodt-sur-Syre', 'lux'=>'Rued-Sir', 'municipality'=>'Betzdorf', 'canton'=>'Grevenmacher', 'lat'=>49.6640, 'lng'=>6.3030 ],
        'roodt-eisch' => [ 'name'=>'Roodt/Eisch', 'lux'=>'Rued-Atert', 'municipality'=>'Habscht', 'canton'=>'Capellen', 'lat'=>49.7210, 'lng'=>5.9860 ],
        'roost-bissen' => [ 'name'=>'Roost (Bissen)', 'lux'=>'Rouscht', 'municipality'=>'Bissen', 'canton'=>'Mersch', 'lat'=>49.7950, 'lng'=>6.0890 ],
        'rosport' => [ 'name'=>'Rosport', 'lux'=>'Rouspert', 'municipality'=>'Rosport-Mompach', 'canton'=>'Echternach', 'lat'=>49.8050, 'lng'=>6.5020 ],
        'rossmuhle' => [ 'name'=>'Rossmühle', 'lux'=>'Rossmillen', 'municipality'=>'Clervaux', 'canton'=>'Clervaux', 'lat'=>50.0910, 'lng'=>6.0820 ],
        'roullingen' => [ 'name'=>'Roullingen', 'lux'=>'Rulljen', 'municipality'=>'Wiltz', 'canton'=>'Wiltz', 'lat'=>49.9570, 'lng'=>5.9180 ],
        'rumelange' => [ 'name'=>'Rumelange', 'lux'=>'Rëmeleng', 'municipality'=>'Rumelange', 'canton'=>'Esch/Alzette', 'lat'=>49.4600, 'lng'=>6.0310 ],
        'rumlange' => [ 'name'=>'Rumlange', 'lux'=>'Rëmleng', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0840, 'lng'=>5.9670 ],
        'saeul' => [ 'name'=>'Saeul', 'lux'=>'Sëll', 'municipality'=>'Saeul', 'canton'=>'Redange', 'lat'=>49.7264, 'lng'=>5.9867 ],
        'sandweiler' => [ 'name'=>'Sandweiler', 'lux'=>'Sandweiler', 'municipality'=>'Sandweiler', 'canton'=>'Luxembourg', 'lat'=>49.6172, 'lng'=>6.2183 ],
        'sanem' => [ 'name'=>'Sanem', 'lux'=>'Suessem', 'municipality'=>'Sanem', 'canton'=>'Esch/Alzette', 'lat'=>49.5481, 'lng'=>5.9289 ],
        'sassel' => [ 'name'=>'Sassel', 'lux'=>'Saassel', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0833, 'lng'=>5.9333 ],
        'savelborn-nommern' => [ 'name'=>'Savelborn (Nommern)', 'lux'=>'Savelbur', 'municipality'=>'Nommern', 'canton'=>'Mersch', 'lat'=>49.8080, 'lng'=>6.2410 ],
        'savelborn-waldbillig' => [ 'name'=>'Savelborn (Waldbillig)', 'lux'=>'Savelbur', 'municipality'=>'Waldbillig', 'canton'=>'Echternach', 'lat'=>49.8130, 'lng'=>6.2550 ],
        'schandel' => [ 'name'=>'Schandel', 'lux'=>'Schandel', 'municipality'=>'Useldange', 'canton'=>'Redange', 'lat'=>49.7750, 'lng'=>5.9750 ],
        'scheedhaff' => [ 'name'=>'Scheedhaff', 'lux'=>'Scheedhaff', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6100, 'lng'=>6.1833 ],
        'scheidel' => [ 'name'=>'Scheidel', 'lux'=>'Scheedel', 'municipality'=>'Bourscheid', 'canton'=>'Diekirch', 'lat'=>49.8917, 'lng'=>6.0417 ],
        'scheidgen' => [ 'name'=>'Scheidgen', 'lux'=>'Scheedgen', 'municipality'=>'Consdorf', 'canton'=>'Echternach', 'lat'=>49.7917, 'lng'=>6.3500 ],
        'schengen' => [ 'name'=>'Schengen', 'lux'=>'Schengen', 'municipality'=>'Schengen', 'canton'=>'Remich', 'lat'=>49.4700, 'lng'=>6.3650 ],
        'scherbach' => [ 'name'=>'Scherbach', 'lux'=>'Scherbach', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0500, 'lng'=>5.9167 ],
        'schieren' => [ 'name'=>'Schieren', 'lux'=>'Schieren', 'municipality'=>'Schieren', 'canton'=>'Diekirch', 'lat'=>49.8333, 'lng'=>6.1000 ],
        'schifflange' => [ 'name'=>'Schifflange', 'lux'=>'Schëffleng', 'municipality'=>'Schifflange', 'canton'=>'Esch/Alzette', 'lat'=>49.5064, 'lng'=>6.0128 ],
        'schiltzberg' => [ 'name'=>'Schiltzberg', 'lux'=>'Schiltzberg', 'municipality'=>'Fischbach', 'canton'=>'Mersch', 'lat'=>49.7333, 'lng'=>6.2000 ],
        'schimpach' => [ 'name'=>'Schimpach', 'lux'=>'Schëmpech', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>49.9917, 'lng'=>5.8500 ],
        'schleif' => [ 'name'=>'Schleif', 'lux'=>'Schleif', 'municipality'=>'Winseler', 'canton'=>'Wiltz', 'lat'=>49.9833, 'lng'=>5.8667 ],
        'schleifmuhle' => [ 'name'=>'Schleifmühle', 'lux'=>'Schleifmillen', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6100, 'lng'=>6.1550 ],
        'schlindermanderscheid' => [ 'name'=>'Schlindermanderscheid', 'lux'=>'Schlienermaanschent', 'municipality'=>'Bourscheid', 'canton'=>'Diekirch', 'lat'=>49.9333, 'lng'=>6.0667 ],
        'schoenfels' => [ 'name'=>'Schoenfels', 'lux'=>'Schëndels', 'municipality'=>'Mersch', 'canton'=>'Mersch', 'lat'=>49.7167, 'lng'=>6.0833 ],
        'schoos' => [ 'name'=>'Schoos', 'lux'=>'Schous', 'municipality'=>'Fischbach', 'canton'=>'Mersch', 'lat'=>49.7500, 'lng'=>6.1667 ],
        'schouweiler' => [ 'name'=>'Schouweiler', 'lux'=>'Schuller', 'municipality'=>'Dippach', 'canton'=>'Capellen', 'lat'=>49.5833, 'lng'=>5.9500 ],
        'schrassig' => [ 'name'=>'Schrassig', 'lux'=>'Schrassig', 'municipality'=>'Schuttrange', 'canton'=>'Luxembourg', 'lat'=>49.6167, 'lng'=>6.2333 ],
        'schrondweiler' => [ 'name'=>'Schrondweiler', 'lux'=>'Schrondweiler', 'municipality'=>'Nommern', 'canton'=>'Mersch', 'lat'=>49.7833, 'lng'=>6.1500 ],
        'schuttrange' => [ 'name'=>'Schuttrange', 'lux'=>'Schëtter', 'municipality'=>'Schuttrange', 'canton'=>'Luxembourg', 'lat'=>49.6167, 'lng'=>6.2667 ],
        'schwebach' => [ 'name'=>'Schwebach', 'lux'=>'Schwebach', 'municipality'=>'Saeul', 'canton'=>'Redange', 'lat'=>49.7333, 'lng'=>5.9667 ],
        'schwebsingen' => [ 'name'=>'Schwebsingen', 'lux'=>'Schwéidsbeng', 'municipality'=>'Schengen', 'canton'=>'Remich', 'lat'=>49.5000, 'lng'=>6.3500 ],
        'schweich' => [ 'name'=>'Schweich', 'lux'=>'Schwéich', 'municipality'=>'Beckerich', 'canton'=>'Redange', 'lat'=>49.7200, 'lng'=>5.9250 ],
        'schwiedelbrouch' => [ 'name'=>'Schwiedelbrouch', 'lux'=>'Schwiddelbrouch', 'municipality'=>'Rambrouch', 'canton'=>'Redange', 'lat'=>49.8417, 'lng'=>5.8083 ],
        'selscheid' => [ 'name'=>'Selscheid', 'lux'=>'Selschent', 'municipality'=>'Wiltz', 'canton'=>'Wiltz', 'lat'=>49.9917, 'lng'=>5.9333 ],
        'seltz' => [ 'name'=>'Seltz', 'lux'=>'Selz', 'municipality'=>'Tandel', 'canton'=>'Vianden', 'lat'=>49.8750, 'lng'=>6.2083 ],
        'senningen' => [ 'name'=>'Senningen', 'lux'=>'Senneng', 'municipality'=>'Niederanven', 'canton'=>'Luxembourg', 'lat'=>49.6469, 'lng'=>6.2372 ],
        'senningerberg' => [ 'name'=>'Senningerberg', 'lux'=>'Sennengerbierg', 'municipality'=>'Niederanven', 'canton'=>'Luxembourg', 'lat'=>49.6469, 'lng'=>6.2250 ],
        'septfontaines' => [ 'name'=>'Septfontaines', 'lux'=>'Simmer', 'municipality'=>'Habscht', 'canton'=>'Capellen', 'lat'=>49.7000, 'lng'=>5.9667 ],
        'siebenaler' => [ 'name'=>'Siebenaler', 'lux'=>'Siwwenaler', 'municipality'=>'Clervaux', 'canton'=>'Clervaux', 'lat'=>50.0000, 'lng'=>6.0333 ],
        'simmerfarm' => [ 'name'=>'Simmerfarm', 'lux'=>'Simmerfarm', 'municipality'=>'Habscht', 'canton'=>'Capellen', 'lat'=>49.7000, 'lng'=>5.9833 ],
        'simmerschmelz' => [ 'name'=>'Simmerschmelz', 'lux'=>'Simmerschmelz', 'municipality'=>'Habscht', 'canton'=>'Capellen', 'lat'=>49.6917, 'lng'=>5.9833 ],
        'soleuvre' => [ 'name'=>'Soleuvre', 'lux'=>'Zolwer', 'municipality'=>'Sanem', 'canton'=>'Esch/Alzette', 'lat'=>49.5167, 'lng'=>5.9333 ],
        'sonlez' => [ 'name'=>'Sonlez', 'lux'=>'Soller', 'municipality'=>'Winseler', 'canton'=>'Wiltz', 'lat'=>49.9583, 'lng'=>5.8333 ],
        'sprinkange' => [ 'name'=>'Sprinkange', 'lux'=>'Sprénkeng', 'municipality'=>'Dippach', 'canton'=>'Capellen', 'lat'=>49.5833, 'lng'=>5.9667 ],
        'stadtbredimus' => [ 'name'=>'Stadtbredimus', 'lux'=>'Stadbriedemes', 'municipality'=>'Stadtbredimus', 'canton'=>'Remich', 'lat'=>49.5667, 'lng'=>6.3667 ],
        'staffelstein' => [ 'name'=>'Staffelstein', 'lux'=>'Staffelsteen', 'municipality'=>'Mersch', 'canton'=>'Mersch', 'lat'=>49.7610, 'lng'=>6.1150 ],
        'stegen' => [ 'name'=>'Stegen', 'lux'=>'Steeën', 'municipality'=>'Vallée de l\'Ernz', 'canton'=>'Diekirch', 'lat'=>49.8333, 'lng'=>6.1667 ],
        'steinfort' => [ 'name'=>'Steinfort', 'lux'=>'Stengefort', 'municipality'=>'Steinfort', 'canton'=>'Capellen', 'lat'=>49.6667, 'lng'=>5.9167 ],
        'steinheim' => [ 'name'=>'Steinheim', 'lux'=>'Steenem', 'municipality'=>'Rosport-Mompach', 'canton'=>'Echternach', 'lat'=>49.8167, 'lng'=>6.4833 ],
        'steinsel' => [ 'name'=>'Steinsel', 'lux'=>'Steesel', 'municipality'=>'Steinsel', 'canton'=>'Luxembourg', 'lat'=>49.6761, 'lng'=>6.1250 ],
        'stockem' => [ 'name'=>'Stockem', 'lux'=>'Stackem', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0500, 'lng'=>5.9667 ],
        'stolzembourg' => [ 'name'=>'Stolzembourg', 'lux'=>'Stolzebuerg', 'municipality'=>'Putscheid', 'canton'=>'Vianden', 'lat'=>49.9667, 'lng'=>6.1667 ],
        'strassen' => [ 'name'=>'Strassen', 'lux'=>'Stroossen', 'municipality'=>'Strassen', 'canton'=>'Luxembourg', 'lat'=>49.6206, 'lng'=>6.0733 ],
        'stuppicht' => [ 'name'=>'Stuppicht', 'lux'=>'Stuppecht', 'municipality'=>'Fischbach', 'canton'=>'Mersch', 'lat'=>49.7333, 'lng'=>6.1500 ],
        'surre' => [ 'name'=>'Surré', 'lux'=>'Siri', 'municipality'=>'Boulaide', 'canton'=>'Wiltz', 'lat'=>49.9000, 'lng'=>5.7833 ],
        'syren' => [ 'name'=>'Syren', 'lux'=>'Siren', 'municipality'=>'Weiler-la-Tour', 'canton'=>'Luxembourg', 'lat'=>49.5667, 'lng'=>6.2167 ],
        'tadler' => [ 'name'=>'Tadler', 'lux'=>'Tadler', 'municipality'=>'Esch-sur-Sûre', 'canton'=>'Wiltz', 'lat'=>49.9083, 'lng'=>5.9917 ],
        'tandel' => [ 'name'=>'Tandel', 'lux'=>'Tandel', 'municipality'=>'Tandel', 'canton'=>'Vianden', 'lat'=>49.8967, 'lng'=>6.1822 ],
        'tarchamps' => [ 'name'=>'Tarchamps', 'lux'=>'Kauneref', 'municipality'=>'Lac de la Haute-Sûre', 'canton'=>'Wiltz', 'lat'=>49.9333, 'lng'=>5.7833 ],
        'tetange' => [ 'name'=>'Tétange', 'lux'=>'Téiteng', 'municipality'=>'Kayl', 'canton'=>'Esch/Alzette', 'lat'=>49.4750, 'lng'=>6.0417 ],
        'tintesmuhle' => [ 'name'=>'Tintesmühle', 'lux'=>'Tintesmillen', 'municipality'=>'Clervaux', 'canton'=>'Clervaux', 'lat'=>50.0833, 'lng'=>6.1167 ],
        'trintange' => [ 'name'=>'Trintange', 'lux'=>'Trinteng', 'municipality'=>'Waldbredimus', 'canton'=>'Remich', 'lat'=>49.5667, 'lng'=>6.2833 ],
        'troine' => [ 'name'=>'Troine', 'lux'=>'Tratten', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0333, 'lng'=>5.8833 ],
        'troine-route' => [ 'name'=>'Troine-Route', 'lux'=>'Tratter Strooss', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0333, 'lng'=>5.8667 ],
        'troisvierges' => [ 'name'=>'Troisvierges', 'lux'=>'Ulfleng', 'municipality'=>'Troisvierges', 'canton'=>'Clervaux', 'lat'=>50.1167, 'lng'=>6.0000 ],
        'tuntange' => [ 'name'=>'Tuntange', 'lux'=>'Tënten', 'municipality'=>'Helperknapp', 'canton'=>'Mersch', 'lat'=>49.7167, 'lng'=>6.0167 ],
        'ubersyren' => [ 'name'=>'Übersyren', 'lux'=>'Iwwersiren', 'municipality'=>'Schuttrange', 'canton'=>'Luxembourg', 'lat'=>49.6333, 'lng'=>6.2833 ],
        'unterschlinder' => [ 'name'=>'Unterschlinder', 'lux'=>'Unterschlinder', 'municipality'=>'Parc Hosingen', 'canton'=>'Clervaux', 'lat'=>49.9500, 'lng'=>6.0667 ],
        'urspelt' => [ 'name'=>'Urspelt', 'lux'=>'Ischpelt', 'municipality'=>'Clervaux', 'canton'=>'Clervaux', 'lat'=>50.0750, 'lng'=>6.0417 ],
        'useldange' => [ 'name'=>'Useldange', 'lux'=>'Useldéng', 'municipality'=>'Useldange', 'canton'=>'Redange', 'lat'=>49.7667, 'lng'=>5.9833 ],
        'vianden' => [ 'name'=>'Vianden', 'lux'=>'Veianen', 'municipality'=>'Vianden', 'canton'=>'Vianden', 'lat'=>49.9333, 'lng'=>6.2167 ],
        'vichten' => [ 'name'=>'Vichten', 'lux'=>'Viichten', 'municipality'=>'Vichten', 'canton'=>'Redange', 'lat'=>49.8000, 'lng'=>6.0000 ],
        'wahl' => [ 'name'=>'Wahl', 'lux'=>'Wal', 'municipality'=>'Wahl', 'canton'=>'Redange', 'lat'=>49.8333, 'lng'=>5.9167 ],
        'wahlhausen' => [ 'name'=>'Wahlhausen', 'lux'=>'Wahlhausen', 'municipality'=>'Parc Hosingen', 'canton'=>'Clervaux', 'lat'=>49.9833, 'lng'=>6.1333 ],
        'waldbillig' => [ 'name'=>'Waldbillig', 'lux'=>'Waldbëlleg', 'municipality'=>'Waldbillig', 'canton'=>'Echternach', 'lat'=>49.7917, 'lng'=>6.2833 ],
        'waldbredimus' => [ 'name'=>'Waldbredimus', 'lux'=>'Waldbriedemes', 'municipality'=>'Waldbredimus', 'canton'=>'Remich', 'lat'=>49.5583, 'lng'=>6.2875 ],
        'waldhof' => [ 'name'=>'Waldhof', 'lux'=>'Waldhaff', 'municipality'=>'Niederanven', 'canton'=>'Luxembourg', 'lat'=>49.6583, 'lng'=>6.1833 ],
        'walferdange' => [ 'name'=>'Walferdange', 'lux'=>'Walfer', 'municipality'=>'Walferdange', 'canton'=>'Luxembourg', 'lat'=>49.6583, 'lng'=>6.1372 ],
        'wallendorf-pont' => [ 'name'=>'Wallendorf-Pont', 'lux'=>'Wallendorfer Bréck', 'municipality'=>'Reisdorf', 'canton'=>'Diekirch', 'lat'=>49.8833, 'lng'=>6.2833 ],
        'walsdorf' => [ 'name'=>'Walsdorf', 'lux'=>'Walsdorf', 'municipality'=>'Tandel', 'canton'=>'Vianden', 'lat'=>49.9167, 'lng'=>6.1667 ],
        'warken' => [ 'name'=>'Warken', 'lux'=>'Warken', 'municipality'=>'Ettelbruck', 'canton'=>'Diekirch', 'lat'=>49.8583, 'lng'=>6.1000 ],
        'wasserbillig' => [ 'name'=>'Wasserbillig', 'lux'=>'Waasserbëlleg', 'municipality'=>'Mertert', 'canton'=>'Grevenmacher', 'lat'=>49.7167, 'lng'=>6.5000 ],
        'watrange' => [ 'name'=>'Watrange', 'lux'=>'Watrange', 'municipality'=>'Winseler', 'canton'=>'Wiltz', 'lat'=>49.9500, 'lng'=>5.8333 ],
        'wecker' => [ 'name'=>'Wecker', 'lux'=>'Wecker', 'municipality'=>'Biwer', 'canton'=>'Grevenmacher', 'lat'=>49.7000, 'lng'=>6.3833 ],
        'weicherdange' => [ 'name'=>'Weicherdange', 'lux'=>'Wäicherdang', 'municipality'=>'Clervaux', 'canton'=>'Clervaux', 'lat'=>50.0333, 'lng'=>5.9917 ],
        'weidingen' => [ 'name'=>'Weidingen', 'lux'=>'Wegdichen', 'municipality'=>'Wiltz', 'canton'=>'Wiltz', 'lat'=>49.9667, 'lng'=>5.9500 ],
        'weiler-putscheid' => [ 'name'=>'Weiler (Putscheid)', 'lux'=>'Weller', 'municipality'=>'Putscheid', 'canton'=>'Vianden', 'lat'=>49.9417, 'lng'=>6.1250 ],
        'weiler-wincrange' => [ 'name'=>'Weiler (Wincrange)', 'lux'=>'Weiler', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0333, 'lng'=>5.8667 ],
        'weiler-la-tour' => [ 'name'=>'Weiler-la-Tour', 'lux'=>'Weiler zum Tuer', 'municipality'=>'Weiler-la-Tour', 'canton'=>'Luxembourg', 'lat'=>49.5444, 'lng'=>6.2028 ],
        'weilerbach' => [ 'name'=>'Weilerbach', 'lux'=>'Weilerbaach', 'municipality'=>'Berdorf', 'canton'=>'Echternach', 'lat'=>49.8333, 'lng'=>6.3833 ],
        'weimershof' => [ 'name'=>'Weimershof', 'lux'=>'Weimeschhaff', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6250, 'lng'=>6.1500 ],
        'weimerskirch' => [ 'name'=>'Weimerskirch', 'lux'=>'Weimeschkierch', 'municipality'=>'Luxembourg', 'canton'=>'Luxembourg', 'lat'=>49.6280, 'lng'=>6.1380 ],
        'weiswampach' => [ 'name'=>'Weiswampach', 'lux'=>'Wäiswampech', 'municipality'=>'Weiswampach', 'canton'=>'Clervaux', 'lat'=>50.1333, 'lng'=>6.0667 ],
        'welfrange' => [ 'name'=>'Welfrange', 'lux'=>'Welfreng', 'municipality'=>'Dalheim', 'canton'=>'Remich', 'lat'=>49.5417, 'lng'=>6.2333 ],
        'wellenstein' => [ 'name'=>'Wellenstein', 'lux'=>'Welleschten', 'municipality'=>'Schengen', 'canton'=>'Remich', 'lat'=>49.5244, 'lng'=>6.3431 ],
        'welscheid' => [ 'name'=>'Welscheid', 'lux'=>'Welschent', 'municipality'=>'Bourscheid', 'canton'=>'Diekirch', 'lat'=>49.8833, 'lng'=>6.0667 ],
        'welsdorf' => [ 'name'=>'Welsdorf', 'lux'=>'Welsdref', 'municipality'=>'Colmar-Berg', 'canton'=>'Mersch', 'lat'=>49.8000, 'lng'=>6.1000 ],
        'wemperhardt' => [ 'name'=>'Wemperhardt', 'lux'=>'Wemperhaart', 'municipality'=>'Weiswampach', 'canton'=>'Clervaux', 'lat'=>50.1500, 'lng'=>6.0500 ],
        'weydig' => [ 'name'=>'Weydig', 'lux'=>'Weydeg', 'municipality'=>'Biwer', 'canton'=>'Grevenmacher', 'lat'=>49.7167, 'lng'=>6.4000 ],
        'weyer' => [ 'name'=>'Weyer', 'lux'=>'Weyer', 'municipality'=>'Fischbach', 'canton'=>'Mersch', 'lat'=>49.7667, 'lng'=>6.2000 ],
        'wickrange' => [ 'name'=>'Wickrange', 'lux'=>'Wickreng', 'municipality'=>'Reckange-sur-Mess', 'canton'=>'Esch/Alzette', 'lat'=>49.5458, 'lng'=>6.0219 ],
        'wiltz' => [ 'name'=>'Wiltz', 'lux'=>'Wolz', 'municipality'=>'Wiltz', 'canton'=>'Wiltz', 'lat'=>49.9667, 'lng'=>5.9333 ],
        'wilwerdange' => [ 'name'=>'Wilwerdange', 'lux'=>'Wilwerdang', 'municipality'=>'Troisvierges', 'canton'=>'Clervaux', 'lat'=>50.1333, 'lng'=>6.0167 ],
        'wilwerwiltz' => [ 'name'=>'Wilwerwiltz', 'lux'=>'Wëlwerwolz', 'municipality'=>'Kiischpelt', 'canton'=>'Wiltz', 'lat'=>49.9889, 'lng'=>5.9917 ],
        'wincrange' => [ 'name'=>'Wincrange', 'lux'=>'Wincrange', 'municipality'=>'Wincrange', 'canton'=>'Clervaux', 'lat'=>50.0533, 'lng'=>5.9144 ],
        'windhof-koerich' => [ 'name'=>'Windhof (Koerich)', 'lux'=>'Wandhaff', 'municipality'=>'Koerich', 'canton'=>'Capellen', 'lat'=>49.6469, 'lng'=>5.9583 ],
        'winseler' => [ 'name'=>'Winseler', 'lux'=>'Winseler', 'municipality'=>'Winseler', 'canton'=>'Wiltz', 'lat'=>49.9667, 'lng'=>5.8833 ],
        'wintrange' => [ 'name'=>'Wintrange', 'lux'=>'Wëntreng', 'municipality'=>'Schengen', 'canton'=>'Remich', 'lat'=>49.5000, 'lng'=>6.3500 ],
        'wirtgensmuhle' => [ 'name'=>'Wirtgensmühle', 'lux'=>'Wirtgensmillen', 'municipality'=>'Clervaux', 'canton'=>'Clervaux', 'lat'=>50.0833, 'lng'=>6.0333 ],
        'wolper' => [ 'name'=>'Wolper', 'lux'=>'Wolper', 'municipality'=>'Consdorf', 'canton'=>'Echternach', 'lat'=>49.7833, 'lng'=>6.3333 ],
        'wolwelange' => [ 'name'=>'Wolwelange', 'lux'=>'Wolwen', 'municipality'=>'Rambrouch', 'canton'=>'Redange', 'lat'=>49.8333, 'lng'=>5.7667 ],
        'wormeldange' => [ 'name'=>'Wormeldange', 'lux'=>'Wuermeldeng', 'municipality'=>'Wormeldange', 'canton'=>'Grevenmacher', 'lat'=>49.6111, 'lng'=>6.4056 ],
        'wormeldange-haut' => [ 'name'=>'Wormeldange-Haut', 'lux'=>'Wuermer Bierg', 'municipality'=>'Wormeldange', 'canton'=>'Grevenmacher', 'lat'=>49.6111, 'lng'=>6.3833 ],
        'zittig' => [ 'name'=>'Zittig', 'lux'=>'Zitteg', 'municipality'=>'Bech', 'canton'=>'Echternach', 'lat'=>49.7500, 'lng'=>6.3333 ],
    ];
}
